.list off
.ifndef MAP_TILE_PROP_INC
MAP_TILE_PROP_INC = 1

.global MapTileProp, MapTilePropPtrs

MAP_TILE_PROP_NONE                      = $00  ; 0
MAP_TILE_PROP_FIGARO_CASTLE             = $01  ; 1
MAP_TILE_PROP_DOMA_CASTLE               = $02  ; 2
MAP_TILE_PROP_VILLAGE_EXT_1             = $03  ; 3
MAP_TILE_PROP_TOWN_EXT                  = $04  ; 4
MAP_TILE_PROP_CASTLE_INT                = $05  ; 5
MAP_TILE_PROP_CAVES                     = $06  ; 6
MAP_TILE_PROP_TOWN_INT                  = $07  ; 7
MAP_TILE_PROP_NARSHE_EXT                = $08  ; 8
MAP_TILE_PROP_CAVES_FURNITURE           = $09  ; 9
MAP_TILE_PROP_CASTLE_BASEMENT           = $0a  ; 10
MAP_TILE_PROP_VILLAGE_EXT_2             = $0b  ; 11
MAP_TILE_PROP_MOUNTAINS_EXT             = $0c  ; 12
MAP_TILE_PROP_TRAIN_EXT                 = $0d  ; 13
MAP_TILE_PROP_ZOZO                      = $0e  ; 14
MAP_TILE_PROP_FLOATING_ISLAND           = $0f  ; 15
MAP_TILE_PROP_MOUNTAINS_INT             = $10  ; 16
MAP_TILE_PROP_DOCKS                     = $11  ; 17
MAP_TILE_PROP_NARSHE_INTRO              = $12  ; 18
MAP_TILE_PROP_TRAIN_INT                 = $13  ; 19
MAP_TILE_PROP_IMP_CAMP                  = $14  ; 20
MAP_TILE_PROP_IMP_CASTLE_EXT            = $15  ; 21
MAP_TILE_PROP_AIRSHIP_EXT               = $16  ; 22
MAP_TILE_PROP_AIRSHIP_INT               = $17  ; 23
MAP_TILE_PROP_IMP_CASTLE_INT            = $18  ; 24
MAP_TILE_PROP_SNOWFIELDS                = $19  ; 25
MAP_TILE_PROP_FOREST                    = $1a  ; 26
MAP_TILE_PROP_VECTOR                    = $1b  ; 27
MAP_TILE_PROP_RIVER                     = $1c  ; 28
MAP_TILE_PROP_OPERA_HOUSE               = $1d  ; 29
MAP_TILE_PROP_DESTROYED_TOWN            = $1e  ; 30
MAP_TILE_PROP_MAGITEK_FACTORY           = $1f  ; 31
MAP_TILE_PROP_DARILLS_TOMB              = $20  ; 32
MAP_TILE_PROP_OPERA_LOBBY               = $21  ; 33
MAP_TILE_PROP_BURNING_BUILDING          = $22  ; 34
MAP_TILE_PROP_SEALED_GATE               = $23  ; 35
MAP_TILE_PROP_MAGITEK_LAB_1             = $24  ; 36
MAP_TILE_PROP_MAGITEK_LAB_2             = $25  ; 37
MAP_TILE_PROP_BEACH                     = $26  ; 38
MAP_TILE_PROP_CYANS_DREAM               = $27  ; 39
MAP_TILE_PROP_KEFKAS_TOWER_1            = $28  ; 40
MAP_TILE_PROP_KEFKAS_TOWER_2            = $29  ; 41

MAP_TILE_PROP_ARRAY_LENGTH              = $2a  ; 42

.endif
.list on
