.list off
.ifndef OVERLAY_PROP_INC
OVERLAY_PROP_INC = 1

.global OverlayProp, OverlayPropPtrs

OVERLAY_NONE                            = $00  ; 0
OVERLAY_TOWN_EXT                        = $01  ; 1
OVERLAY_CAVES                           = $02  ; 2
OVERLAY_TOWN_INT                        = $03  ; 3
OVERLAY_NARSHE_EXT                      = $04  ; 4
OVERLAY_CAVES_FURNITURE                 = $05  ; 5
OVERLAY_MOUNTAINS_EXT_1                 = $06  ; 6
OVERLAY_TRAIN_EXT                       = $07  ; 7
OVERLAY_ZOZO_EXT                        = $08  ; 8
OVERLAY_TRAIN_INT                       = $09  ; 9
OVERLAY_IMP_CAMP                        = $0a  ; 10
OVERLAY_FOREST                          = $0b  ; 11
OVERLAY_OPERA_HOUSE                     = $0c  ; 12
OVERLAY_DESTROYED_TOWN                  = $0d  ; 13
OVERLAY_MAGITEK_FACTORY                 = $0e  ; 14
OVERLAY_FIGARO_CASTLE_EXT               = $0f  ; 15
OVERLAY_DOMA_EXT                        = $10  ; 16
OVERLAY_VILLAGE_EXT_1                   = $11  ; 17
OVERLAY_CASTLE_INT                      = $12  ; 18
OVERLAY_CASTLE_BASEMENT                 = $13  ; 19
OVERLAY_VILLAGE_EXT_2                   = $14  ; 20
OVERLAY_FLOATING_ISLAND                 = $15  ; 21
OVERLAY_AIRSHIP_EXT                     = $16  ; 22
OVERLAY_AIRSHIP_INT                     = $17  ; 23
OVERLAY_IMP_CASTLE_INT                  = $18  ; 24
OVERLAY_VECTOR_EXT                      = $19  ; 25
OVERLAY_26                              = $1a  ; 26
OVERLAY_MOUNTAINS_INT                   = $1b  ; 27
OVERLAY_IMP_CASTLE_EXT                  = $1c  ; 28
OVERLAY_MAGITEK_LAB                     = $1d  ; 29
OVERLAY_DARILLS_TOMB                    = $1e  ; 30
OVERLAY_KEFKAS_TOWER                    = $1f  ; 31
OVERLAY_32                              = $20  ; 32
OVERLAY_MOUNTAINS_EXT_2                 = $21  ; 33
OVERLAY_SNOWFIELDS                      = $22  ; 34
OVERLAY_35                              = $23  ; 35 (unused)
OVERLAY_36                              = $24  ; 36 (unused)
OVERLAY_37                              = $25  ; 37 (unused)
OVERLAY_38                              = $26  ; 38 (unused)
OVERLAY_39                              = $27  ; 39 (unused)
OVERLAY_40                              = $28  ; 40 (unused)
OVERLAY_41                              = $29  ; 41 (unused)
OVERLAY_42                              = $2a  ; 42 (unused)
OVERLAY_43                              = $2b  ; 43 (unused)
OVERLAY_44                              = $2c  ; 44 (unused)

OVERLAY_PROP_ARRAY_LENGTH               = $2d  ; 45

.endif
.list on
