.list off
.ifndef CHAR_NAME_INC
CHAR_NAME_INC = 1

.global CharName

.scope CHAR_NAME

        .include "assets/text/char_name.ptr"

        ; TERRA                           = 0
        ; LOCKE                           = 1
        ; CYAN                            = 2
        ; SHADOW                          = 3
        ; EDGAR                           = 4
        ; SABIN                           = 5
        ; CELES                           = 6
        ; STRAGO                          = 7
        ; RELM                            = 8
        ; SETZER                          = 9
        ; MOG                             = 10
        ; GAU                             = 11
        ; GOGO                            = 12
        ; UMARO                           = 13
        ; BANON                           = 14
        ; LEO                             = 15
        ; GHOST_1                         = 16
        ; GHOST_2                         = 17
        ; KUPEK                           = 18
        ; KUPOP                           = 19
        ; KUMAMA                          = 20
        ; KUKU                            = 21
        ; KUTAN                           = 22
        ; KUPAN                           = 23
        ; KUSHU                           = 24
        ; KURIN                           = 25
        ; KURU                            = 26
        ; KAMOG                           = 27
        ; SCENARIO_MOG                    = 28
        ; TERRA_INTRO                     = 29
        ; MADUIN                          = 30
        ; SHADOW_COLOSSEUM                = 31
        ; WEDGE                           = 32
        ; VICKS                           = 33
        ; UNUSED_22                       = 34
        ; UNUSED_23                       = 35
        ; UNUSED_24                       = 36
        ; UNUSED_25                       = 37
        ; UNUSED_26                       = 38
        ; UNUSED_27                       = 39
        ; UNUSED_28                       = 40
        ; KEFKA_1                         = 41
        ; KEFKA_2                         = 42
        ; KEFKA_3                         = 43
        ; KEFKA_4                         = 44
        ; KEFKA_5                         = 45
        ; KEFKA_6                         = 46
        ; KEFKA_7                         = 47
        ; TORK                            = 48
        ; JADE                            = 49
        ; CUSTER                          = 50
        ; FABIAN                          = 51
        ; DRAKE                           = 52
        ; SARA                            = 53
        ; CASE                            = 54
        ; SIELE                           = 55
        ; RAY                             = 56
        ; REIKER                          = 57
        ; LANCE                           = 58
        ; BOB                             = 59
        ; PEPPER                          = 60
        ; TAU                             = 61
        ; VICTOR                          = 62
        ; HO                              = 63

.endscope

.endif
.list on
