; ------------------------------------------------------------------------------

.mac make_monster_rage attack2
        .byte ATTACK::BATTLE, ATTACK::attack2
.endmac

; ------------------------------------------------------------------------------

; cf/4600
MonsterRage:
        make_monster_rage SPECIAL                       ; GUARD
        make_monster_rage FIRE                          ; SOLDIER
        make_monster_rage FIRE_2                        ; TEMPLAR
        make_monster_rage WATER_EDGE                    ; NINJA
        make_monster_rage LULLABY                       ; SAMURAI
        make_monster_rage PEARL                         ; OROG
        make_monster_rage BIO                           ; MAG_ROADER_1
        make_monster_rage SHOCK                         ; RETAINER
        make_monster_rage BOLT_2                        ; HAZER
        make_monster_rage CURE_2                        ; DAHLING
        make_monster_rage BOLT_3                        ; RAIN_MAN
        make_monster_rage STONE                         ; BRAWLER
        make_monster_rage L3_MUDDLE                     ; APOKRYPHOS
        make_monster_rage CLEANSWEEP                    ; DARK_FORCE
        make_monster_rage DEMI                          ; WHISPER
        make_monster_rage ELF_FIRE                      ; OVER_MIND
        make_monster_rage X_ZONE                        ; OSTEOSAUR
        make_monster_rage BREAK                         ; COMMANDER
        make_monster_rage SNARE                         ; RHODOX
        make_monster_rage POISON                        ; WERE_RAT
        make_monster_rage NET                           ; URSUS
        make_monster_rage MEGA_VOLT                     ; RHINOTAUR
        make_monster_rage BLIZZARD                      ; STEROIDITE
        make_monster_rage SPECIAL                       ; LEAFER
        make_monster_rage SPECIAL                       ; STRAY_CAT
        make_monster_rage SPECIAL                       ; LOBO
        make_monster_rage SPECIAL                       ; DOBERMAN
        make_monster_rage BLIZZARD                      ; VOMAMMOTH
        make_monster_rage SPECIAL                       ; FIDOR
        make_monster_rage CYCLONIC                      ; BASKERVOR
        make_monster_rage AQUA_RAKE                     ; SURIANDER
        make_monster_rage AQUA_RAKE                     ; CHIMERA
        make_monster_rage METEOR                        ; BEHEMOTH
        make_monster_rage STEP_MINE                     ; MESOSAUR
        make_monster_rage FIRE_BALL                     ; PTERODON
        make_monster_rage SAND_STORM                    ; FOSSILFANG
        make_monster_rage PEARL                         ; WHITE_DRGN
        make_monster_rage N_CROSS                       ; DOOM_DRGN
        make_monster_rage DISASTER                      ; BRACHOSAUR
        make_monster_rage METEO                         ; TYRANOSAUR
        make_monster_rage BREAK                         ; DARK_WIND
        make_monster_rage SPECIAL                       ; BEAKOR
        make_monster_rage SHIMSHAM                      ; VULTURE
        make_monster_rage CYCLONIC                      ; HARPY
        make_monster_rage NET                           ; HERMITCRAB
        make_monster_rage L3_MUDDLE                     ; TRAPPER
        make_monster_rage SPECIAL                       ; HORNET
        make_monster_rage BSERK                         ; CRASSHOPPR
        make_monster_rage MEGA_VOLT                     ; DELTA_BUG
        make_monster_rage SHRAPNEL                      ; GILOMANTIS
        make_monster_rage BIO                           ; TRILIUM
        make_monster_rage CHARM                         ; NIGHTSHADE
        make_monster_rage LIFESHAVER                    ; TUMBLEWEED
        make_monster_rage BIO                           ; BLOOMPIRE
        make_monster_rage SPECIAL                       ; TRILOBITER
        make_monster_rage FLARE                         ; SIEGFRIED_1
        make_monster_rage SPECIAL                       ; NAUTILOID
        make_monster_rage SPECIAL                       ; EXOCITE
        make_monster_rage AQUA_RAKE                     ; ANGUIFORM
        make_monster_rage SLIMER                        ; REACH_FROG
        make_monster_rage BREAK                         ; LIZARD
        make_monster_rage QUAKE                         ; CHICKENLIP
        make_monster_rage SAND_STORM                    ; HOOVER
        make_monster_rage VIRITE                        ; RIDER
        make_monster_rage W_WIND                        ; CHUPON_COLOSSEUM
        make_monster_rage IMP                           ; PIPSQUEAK
        make_monster_rage TEK_LASER                     ; M_TEKARMOR
        make_monster_rage TEK_LASER                     ; SKY_ARMOR
        make_monster_rage SONIC_BOOM                    ; TELSTAR
        make_monster_rage GRAV_BOMB                     ; LETHAL_WPN
        make_monster_rage BLAZE                         ; VAPORITE
        make_monster_rage SLIMER                        ; FLAN
        make_monster_rage LIFESHAVER                    ; ING
        make_monster_rage POISON                        ; HUMPTY
        make_monster_rage BLOW_FISH                     ; BRAINPAN
        make_monster_rage SLIMER                        ; CRULLER
        make_monster_rage BLOW_FISH                     ; CACTROT
        make_monster_rage EXPLODER                      ; REPO_MAN
        make_monster_rage HASTE                         ; HARVESTER
        make_monster_rage BLAZE                         ; BOMB
        make_monster_rage LULLABY                       ; STILL_LIFE
        make_monster_rage METEOR                        ; BOXED_SET
        make_monster_rage ICE_2                         ; SLAMDANCER
        make_monster_rage MAGNITUDE8                    ; HADESGIGAS
        make_monster_rage BREAK                         ; PUG
        make_monster_rage CURE_3                        ; MAGIC_URN
        make_monster_rage MERTON                        ; MOVER
        make_monster_rage DISCHORD                      ; FIGALIZ
        make_monster_rage SLOW_2                        ; BUFFALAX
        make_monster_rage GIGA_VOLT                     ; ASPIK
        make_monster_rage BOLT_2                        ; GHOST
        make_monster_rage STEP_MINE                     ; CRAWLER
        make_monster_rage SPECIAL                       ; SAND_RAY
        make_monster_rage SPECIAL                       ; ARENEID
        make_monster_rage SPECIAL                       ; ACTANEON
        make_monster_rage SAND_STORM                    ; SAND_HORSE
        make_monster_rage ICE_2                         ; DARK_SIDE
        make_monster_rage SOUR_MOUTH                    ; MAD_OSCAR
        make_monster_rage SPECIAL                       ; CRAWLY
        make_monster_rage DOOM                          ; BLEARY
        make_monster_rage WIND_SLASH                    ; MARSHAL
        make_monster_rage SPECIAL                       ; TROOPER
        make_monster_rage CURE_2                        ; GENERAL
        make_monster_rage WIND_SLASH                    ; COVERT
        make_monster_rage STORM                         ; OGOR
        make_monster_rage PEARL                         ; WARLOCK
        make_monster_rage PEARL                         ; MADAM
        make_monster_rage BOLT_2                        ; JOKER
        make_monster_rage STONE                         ; IRON_FIST
        make_monster_rage BOLT_3                        ; GOBLIN
        make_monster_rage IMP                           ; APPARITE
        make_monster_rage FLARE                         ; POWERDEMON
        make_monster_rage DOOM                          ; DISPLAYER
        make_monster_rage SPECIAL                       ; VECTOR_PUP
        make_monster_rage PEARL_WIND                    ; PEEPERS
        make_monster_rage SPECIAL                       ; SEWER_RAT
        make_monster_rage CAVE_IN                       ; SLATTER
        make_monster_rage LIFE_3                        ; RHINOX
        make_monster_rage LIFE                          ; RHOBITE
        make_monster_rage BLASTER                       ; WILD_CAT
        make_monster_rage DRAIN                         ; RED_FANG
        make_monster_rage SPECIAL                       ; BOUNTY_MAN
        make_monster_rage BLIZZARD                      ; TUSKER
        make_monster_rage SPECIAL                       ; RALPH
        make_monster_rage STOP                          ; CHITONID
        make_monster_rage RASP                          ; WART_PUCK
        make_monster_rage SURGE                         ; RHYOS
        make_monster_rage FIRE_3                        ; SRBEHEMOTH_UNDEAD
        make_monster_rage PEARL_WIND                    ; VECTAUR
        make_monster_rage CYCLONIC                      ; WYVERN
        make_monster_rage CONDEMNED                     ; ZOMBONE
        make_monster_rage REVENGE                       ; DRAGON
        make_monster_rage FIRE_3                        ; BRONTAUR
        make_monster_rage DOOM                          ; ALLOSAURUS
        make_monster_rage HASTE2                        ; CIRPIUS
        make_monster_rage AERO                          ; SPRINTER
        make_monster_rage SHIMSHAM                      ; GOBBLER
        make_monster_rage AERO                          ; HARPIAI
        make_monster_rage NET                           ; GLOOMSHELL
        make_monster_rage MUDDLE                        ; DROP
        make_monster_rage SPECIAL                       ; MIND_CANDY
        make_monster_rage BSERK                         ; WEEDFEEDER
        make_monster_rage LAND_SLIDE                    ; LURIDAN
        make_monster_rage SHRAPNEL                      ; TOE_CUTTER
        make_monster_rage SPECIAL                       ; OVER_GRUNK
        make_monster_rage VIRITE                        ; EXORAY
        make_monster_rage LIFESHAVER                    ; CRUSHER
        make_monster_rage QUAKE                         ; UROBUROS
        make_monster_rage SPECIAL                       ; PRIMORDITE
        make_monster_rage MEGAZERK                      ; SKY_CAP
        make_monster_rage SPECIAL                       ; CEPHALER
        make_monster_rage REMEDY                        ; MALIGA
        make_monster_rage SLIMER                        ; GIGAN_TOAD
        make_monster_rage BREAK                         ; GECKOREX
        make_monster_rage QUAKE                         ; CLUCK
        make_monster_rage MAGNITUDE8                    ; LAND_WORM
        make_monster_rage FLASH_RAIN                    ; TEST_RIDER
        make_monster_rage TEK_LASER                     ; PLUTOARMOR
        make_monster_rage STEP_MINE                     ; TOMB_THUMB
        make_monster_rage TEK_LASER                     ; HEAVYARMOR
        make_monster_rage PLASMA                        ; CHASER
        make_monster_rage DISCHORD                      ; SCULLION
        make_monster_rage SPECIAL                       ; POPLIUM
        make_monster_rage PEP_UP                        ; INTANGIR
        make_monster_rage LIFESHAVER                    ; MISFIT
        make_monster_rage BIO                           ; ELAND
        make_monster_rage CLEANSWEEP                    ; ENUO
        make_monster_rage DREAD                         ; DEEP_EYE
        make_monster_rage SHELL                         ; GREASEMONK
        make_monster_rage IMP                           ; NECKHUNTER
        make_monster_rage BLAZE                         ; GRENADE
        make_monster_rage CONDEMNED                     ; CRITIC
        make_monster_rage REVENGE                       ; PAN_DORA
        make_monster_rage OSMOSE                        ; SOULDANCER
        make_monster_rage MAGNITUDE8                    ; GIGANTOS
        make_monster_rage MUTE                          ; MAG_ROADER_2
        make_monster_rage BLASTER                       ; SPEK_TOR
        make_monster_rage GIGA_VOLT                     ; PARASITE
        make_monster_rage BIG_GUARD                     ; EARTHGUARD
        make_monster_rage MAGNITUDE8                    ; COELECITE
        make_monster_rage GIGA_VOLT                     ; ANEMONE
        make_monster_rage FLASH_RAIN                    ; HIPOCAMPUS
        make_monster_rage FIRE                          ; SPECTRE
        make_monster_rage BIO                           ; EVIL_OSCAR
        make_monster_rage SLIMER                        ; SLURM
        make_monster_rage MAGNITUDE8                    ; LATIMERIA
        make_monster_rage OSMOSE                        ; STILLGOING
        make_monster_rage QUAKE                         ; ALLO_VER
        make_monster_rage BLOW_FISH                     ; PHASE
        make_monster_rage PEARL                         ; OUTSIDER
        make_monster_rage LOVE_TOKEN                    ; BARB_E
        make_monster_rage FLASH_RAIN                    ; PARASOUL
        make_monster_rage DRAIN                         ; PM_STALKER
        make_monster_rage SHOCK_WAVE                    ; HEMOPHYTE
        make_monster_rage SAFE                          ; SP_FORCES
        make_monster_rage CURE_2                        ; NOHRABBIT
        make_monster_rage DEMI                          ; WIZARD
        make_monster_rage ELF_FIRE                      ; SCRAPPER
        make_monster_rage GIGA_VOLT                     ; CERITOPS
        make_monster_rage RFLECT                        ; COMMANDO
        make_monster_rage SLIDE                         ; OPINICUS
        make_monster_rage STONE                         ; POPPERS
        make_monster_rage SPECIAL                       ; LUNARIS
        make_monster_rage DEMI                          ; GARM
        make_monster_rage ACID_RAIN                     ; VINDR
        make_monster_rage IMP                           ; KIWOK
        make_monster_rage BLIZZARD                      ; NASTIDON
        make_monster_rage FIRE                          ; RINN
        make_monster_rage SPECIAL                       ; INSECARE
        make_monster_rage SCAN                          ; VERMIN
        make_monster_rage WIND_SLASH                    ; MANTODEA
        make_monster_rage SPECIAL                       ; BOGY
        make_monster_rage LAND_SLIDE                    ; PRUSSIAN
        make_monster_rage STORM                         ; BLACK_DRGN
        make_monster_rage ACID_RAIN                     ; ADAMANCHYT
        make_monster_rage L3_MUDDLE                     ; DANTE
        make_monster_rage CYCLONIC                      ; WIREY_DRGN
        make_monster_rage MEGA_VOLT                     ; DUELLER
        make_monster_rage LIFESHAVER                    ; PSYCHOT
        make_monster_rage PEP_UP                        ; MUUS
        make_monster_rage BOLT_3                        ; KARKASS
        make_monster_rage BOLT_3                        ; PUNISHER
        make_monster_rage EXPLODER                      ; BALLOON
        make_monster_rage VANISH                        ; GABBLDEGAK
        make_monster_rage METEOR                        ; GTBEHEMOTH
        make_monster_rage POISON                        ; SCORPION
        make_monster_rage DISASTER                      ; CHAOS_DRGN
        make_monster_rage TEK_LASER                     ; SPIT_FIRE
        make_monster_rage AQUA_RAKE                     ; VECTAGOYLE
        make_monster_rage FIRE_2                        ; LICH
        make_monster_rage SHIMSHAM                      ; OSPREY
        make_monster_rage HASTE                         ; MAG_ROADER_3
        make_monster_rage STOP                          ; BUG
        make_monster_rage SLEEP                         ; SEA_FLOWER
        make_monster_rage FIRE_BALL                     ; FORTIS
        make_monster_rage POISON                        ; ABOLISHER
        make_monster_rage CYCLONIC                      ; AQUILA
        make_monster_rage PEP_UP                        ; JUNK
        make_monster_rage RAID                          ; MANDRAKE
        make_monster_rage STONE                         ; 1ST_CLASS
        make_monster_rage SLOW_2                        ; TAP_DANCER
        make_monster_rage DOOM                          ; NECROMANCR
        make_monster_rage REVENGE                       ; BORRAS
        make_monster_rage L4_FLARE                      ; MAG_ROADER_4
        make_monster_rage SPECIAL                       ; WILD_RAT
        make_monster_rage SPECIAL                       ; GOLD_BEAR
        make_monster_rage VIRITE                        ; INNOC
        make_monster_rage FIRE_2                        ; TRIXTER
        make_monster_rage SPECIAL                       ; RED_WOLF
        make_monster_rage MERTON                        ; DIDALOS
        make_monster_rage ICE_3                         ; WOOLLY
        make_monster_rage ROULETTE                      ; VETERAN
        make_monster_rage DOOM                          ; SKY_BASE
        make_monster_rage DISCHORD                      ; IRONHITMAN
        make_monster_rage FLARE_STAR                    ; IO
        make_monster_rage SPECIAL                       ; PUGS

; ------------------------------------------------------------------------------
