; ------------------------------------------------------------------------------

; cf/3d00
MonsterControl:

; $0000: MONSTER_GUARD
.byte ATTACK_BATTLE
.byte ATTACK_NONE
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0001: MONSTER_SOLDIER
.byte ATTACK_BATTLE
.byte ATTACK_SCAN
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0002: MONSTER_TEMPLAR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0003: MONSTER_NINJA
.byte ATTACK_BATTLE
.byte ATTACK_FIRE_SKEAN
.byte ATTACK_WATER_EDGE
.byte ATTACK_BOLT_EDGE

; $0004: MONSTER_SAMURAI
.byte ATTACK_BATTLE
.byte ATTACK_FLARE
.byte ATTACK_DOOM
.byte ATTACK_HASTE2

; $0005: MONSTER_OROG
.byte ATTACK_BATTLE
.byte ATTACK_BIO
.byte ATTACK_PEARL
.byte ATTACK_NONE

; $0006: MONSTER_MAG_ROADER_1
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0007: MONSTER_RETAINER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_WIND_SLASH
.byte ATTACK_CONDEMNED

; $0008: MONSTER_HAZER
.byte ATTACK_BATTLE
.byte ATTACK_DRAIN
.byte ATTACK_FIRE
.byte ATTACK_NONE

; $0009: MONSTER_DAHLING
.byte ATTACK_BATTLE
.byte ATTACK_MUTE
.byte ATTACK_CURE_2
.byte ATTACK_NONE

; $000a: MONSTER_RAIN_MAN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BOLT_3
.byte ATTACK_FLASH_RAIN

; $000b: MONSTER_BRAWLER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $000c: MONSTER_APOKRYPHOS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_L3_MUDDLE
.byte ATTACK_L4_FLARE

; $000d: MONSTER_DARK_FORCE
.byte ATTACK_BATTLE
.byte ATTACK_L5_DOOM
.byte ATTACK_CLEANSWEEP
.byte ATTACK_PEARL_WIND

; $000e: MONSTER_WHISPER
.byte ATTACK_BATTLE
.byte ATTACK_FIRE
.byte ATTACK_DEMI
.byte ATTACK_NONE

; $000f: MONSTER_OVER_MIND
.byte ATTACK_BATTLE
.byte ATTACK_DREAD
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0010: MONSTER_OSTEOSAUR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0011: MONSTER_COMMANDER
.byte ATTACK_BATTLE
.byte ATTACK_FIRE
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0012: MONSTER_RHODOX
.byte ATTACK_BATTLE
.byte ATTACK_NONE
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0013: MONSTER_WERE_RAT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0014: MONSTER_URSUS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0015: MONSTER_RHINOTAUR
.byte ATTACK_BATTLE
.byte ATTACK_MEGA_VOLT
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0016: MONSTER_STEROIDITE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BLIZZARD
.byte ATTACK_BLASTER

; $0017: MONSTER_LEAFER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0018: MONSTER_STRAY_CAT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0019: MONSTER_LOBO
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $001a: MONSTER_DOBERMAN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $001b: MONSTER_VOMAMMOTH
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BLIZZARD
.byte ATTACK_NONE

; $001c: MONSTER_FIDOR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $001d: MONSTER_BASKERVOR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BLIZZARD
.byte ATTACK_NONE

; $001e: MONSTER_SURIANDER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_AQUA_RAKE
.byte ATTACK_NONE

; $001f: MONSTER_CHIMERA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_AQUA_RAKE
.byte ATTACK_BLIZZARD

; $0020: MONSTER_BEHEMOTH
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_METEOR
.byte ATTACK_FIRE_3

; $0021: MONSTER_MESOSAUR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_STEP_MINE
.byte ATTACK_NONE

; $0022: MONSTER_PTERODON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_FIRE_BALL
.byte ATTACK_NONE

; $0023: MONSTER_FOSSILFANG
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SAND_STORM
.byte ATTACK_X_ZONE

; $0024: MONSTER_WHITE_DRGN
.byte ATTACK_BATTLE
.byte ATTACK_PEARL
.byte ATTACK_PEARL
.byte ATTACK_PEARL

; $0025: MONSTER_DOOM_DRGN
.byte ATTACK_BATTLE
.byte ATTACK_FALLEN_ONE
.byte ATTACK_N_CROSS
.byte ATTACK_S_CROSS

; $0026: MONSTER_BRACHOSAUR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0027: MONSTER_TYRANOSAUR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SLOW
.byte ATTACK_HASTE

; $0028: MONSTER_DARK_WIND
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0029: MONSTER_BEAKOR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $002a: MONSTER_VULTURE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SHIMSHAM
.byte ATTACK_NONE

; $002b: MONSTER_HARPY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_CYCLONIC
.byte ATTACK_AERO

; $002c: MONSTER_HERMITCRAB
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NET
.byte ATTACK_NONE

; $002d: MONSTER_TRAPPER
.byte ATTACK_BATTLE
.byte ATTACK_L5_DOOM
.byte ATTACK_L3_MUDDLE
.byte ATTACK_L4_FLARE

; $002e: MONSTER_HORNET
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $002f: MONSTER_CRASSHOPPR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0030: MONSTER_DELTA_BUG
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MEGA_VOLT
.byte ATTACK_NONE

; $0031: MONSTER_GILOMANTIS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SHRAPNEL
.byte ATTACK_NONE

; $0032: MONSTER_TRILIUM
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0033: MONSTER_NIGHTSHADE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_CHARM
.byte ATTACK_NONE

; $0034: MONSTER_TUMBLEWEED
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_LIFESHAVER
.byte ATTACK_NONE

; $0035: MONSTER_BLOOMPIRE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BIO
.byte ATTACK_DOOM

; $0036: MONSTER_TRILOBITER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_POISON
.byte ATTACK_NONE

; $0037: MONSTER_SIEGFRIED_1
.byte ATTACK_BATTLE
.byte ATTACK_HYPERDRIVE
.byte ATTACK_SHRAPNEL
.byte ATTACK_BATTLE

; $0038: MONSTER_NAUTILOID
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0039: MONSTER_EXOCITE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $003a: MONSTER_ANGUIFORM
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_AQUA_RAKE
.byte ATTACK_NONE

; $003b: MONSTER_REACH_FROG
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SLIMER
.byte ATTACK_NONE

; $003c: MONSTER_LIZARD
.byte ATTACK_BATTLE
.byte ATTACK_BREAK
.byte ATTACK_DISCHORD
.byte ATTACK_NONE

; $003d: MONSTER_CHICKENLIP
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_QUAKE
.byte ATTACK_NONE

; $003e: MONSTER_HOOVER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SAND_STORM
.byte ATTACK_QUAKE

; $003f: MONSTER_RIDER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_VIRITE
.byte ATTACK_NONE

; $0040: MONSTER_CHUPON_COLOSSEUM
.byte ATTACK_BATTLE
.byte ATTACK_SNEEZE
.byte ATTACK_SNEEZE
.byte ATTACK_SNEEZE

; $0041: MONSTER_PIPSQUEAK
.byte ATTACK_BATTLE
.byte ATTACK_DEMI
.byte ATTACK_QUARTR
.byte ATTACK_NONE

; $0042: MONSTER_M_TEKARMOR
.byte ATTACK_BATTLE
.byte ATTACK_TEK_LASER
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0043: MONSTER_SKY_ARMOR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_TEK_LASER
.byte ATTACK_NONE

; $0044: MONSTER_TELSTAR
.byte ATTACK_BATTLE
.byte ATTACK_TEK_LASER
.byte ATTACK_FIRE_BALL
.byte ATTACK_NONE

; $0045: MONSTER_LETHAL_WPN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_TEK_LASER
.byte ATTACK_ABSOLUTE0

; $0046: MONSTER_VAPORITE
.byte ATTACK_BATTLE
.byte ATTACK_SLOW
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0047: MONSTER_FLAN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SLIMER
.byte ATTACK_NONE

; $0048: MONSTER_ING
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_LIFESHAVER
.byte ATTACK_NONE

; $0049: MONSTER_HUMPTY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_POISON
.byte ATTACK_NONE

; $004a: MONSTER_BRAINPAN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BLOW_FISH
.byte ATTACK_NONE

; $004b: MONSTER_CRULLER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SLIMER
.byte ATTACK_NONE

; $004c: MONSTER_CACTROT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BLOW_FISH
.byte ATTACK_NONE

; $004d: MONSTER_REPO_MAN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SPECIAL
.byte ATTACK_SPECIAL

; $004e: MONSTER_HARVESTER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_DRAIN
.byte ATTACK_NONE

; $004f: MONSTER_BOMB
.byte ATTACK_BATTLE
.byte ATTACK_EXPLODER
.byte ATTACK_BLAZE
.byte ATTACK_NONE

; $0050: MONSTER_STILL_LIFE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_LULLABY
.byte ATTACK_CONDEMNED

; $0051: MONSTER_BOXED_SET
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_METEOR
.byte ATTACK_LODE_STONE

; $0052: MONSTER_SLAMDANCER
.byte ATTACK_BATTLE
.byte ATTACK_FIRE_2
.byte ATTACK_ICE_2
.byte ATTACK_BOLT_2

; $0053: MONSTER_HADESGIGAS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MAGNITUDE8
.byte ATTACK_NONE

; $0054: MONSTER_PUG
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BREAK
.byte ATTACK_NONE

; $0055: MONSTER_MAGIC_URN
.byte ATTACK_BATTLE
.byte ATTACK_REMEDY
.byte ATTACK_CURE_3
.byte ATTACK_W_WIND

; $0056: MONSTER_MOVER
.byte ATTACK_BATTLE
.byte ATTACK_BIG_GUARD
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0057: MONSTER_FIGALIZ
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_DISCHORD
.byte ATTACK_RAID

; $0058: MONSTER_BUFFALAX
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SURGE
.byte ATTACK_NONE

; $0059: MONSTER_ASPIK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_GIGA_VOLT
.byte ATTACK_NONE

; $005a: MONSTER_GHOST
.byte ATTACK_BATTLE
.byte ATTACK_FIRE
.byte ATTACK_NONE
.byte ATTACK_NONE

; $005b: MONSTER_CRAWLER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_STEP_MINE
.byte ATTACK_NONE

; $005c: MONSTER_SAND_RAY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $005d: MONSTER_ARENEID
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $005e: MONSTER_ACTANEON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $005f: MONSTER_SAND_HORSE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SAND_STORM
.byte ATTACK_NONE

; $0060: MONSTER_DARK_SIDE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_FIRE
.byte ATTACK_NONE

; $0061: MONSTER_MAD_OSCAR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SOUR_MOUTH
.byte ATTACK_NONE

; $0062: MONSTER_CRAWLY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MAGNITUDE8
.byte ATTACK_NONE

; $0063: MONSTER_BLEARY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_DREAD
.byte ATTACK_NONE

; $0064: MONSTER_MARSHAL
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BOLT_2
.byte ATTACK_NONE

; $0065: MONSTER_TROOPER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0066: MONSTER_GENERAL
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_CURE_2
.byte ATTACK_NONE

; $0067: MONSTER_COVERT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_WIND_SLASH
.byte ATTACK_RAGE

; $0068: MONSTER_OGOR
.byte ATTACK_BATTLE
.byte ATTACK_COLD_DUST
.byte ATTACK_PEARL_WIND
.byte ATTACK_NONE

; $0069: MONSTER_WARLOCK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_PEARL
.byte ATTACK_NONE

; $006a: MONSTER_MADAM
.byte ATTACK_BATTLE
.byte ATTACK_FLARE
.byte ATTACK_PEARL
.byte ATTACK_ICE_3

; $006b: MONSTER_JOKER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BOLT_2
.byte ATTACK_ACID_RAIN

; $006c: MONSTER_IRON_FIST
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_STONE
.byte ATTACK_NONE

; $006d: MONSTER_GOBLIN
.byte ATTACK_BATTLE
.byte ATTACK_FIRE_3
.byte ATTACK_BOLT_3
.byte ATTACK_ICE_3

; $006e: MONSTER_APPARITE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_IMP
.byte ATTACK_NONE

; $006f: MONSTER_POWERDEMON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_FLARE
.byte ATTACK_NONE

; $0070: MONSTER_DISPLAYER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_DOOM
.byte ATTACK_X_ZONE

; $0071: MONSTER_VECTOR_PUP
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0072: MONSTER_PEEPERS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_PEARL_WIND
.byte ATTACK_NONE

; $0073: MONSTER_SEWER_RAT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0074: MONSTER_SLATTER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0075: MONSTER_RHINOX
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_LIFE_3
.byte ATTACK_NONE

; $0076: MONSTER_RHOBITE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0077: MONSTER_WILD_CAT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BLASTER
.byte ATTACK_NONE

; $0078: MONSTER_RED_FANG
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0079: MONSTER_BOUNTY_MAN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $007a: MONSTER_TUSKER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $007b: MONSTER_RALPH
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $007c: MONSTER_CHITONID
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $007d: MONSTER_WART_PUCK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_EXPLODER
.byte ATTACK_NONE

; $007e: MONSTER_RHYOS
.byte ATTACK_BATTLE
.byte ATTACK_FLARE_STAR
.byte ATTACK_SURGE
.byte ATTACK_AERO

; $007f: MONSTER_SRBEHEMOTH_UNDEAD
.byte ATTACK_BATTLE
.byte ATTACK_BATTLE
.byte ATTACK_BATTLE
.byte ATTACK_BATTLE

; $0080: MONSTER_VECTAUR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_PEARL_WIND
.byte ATTACK_NONE

; $0081: MONSTER_WYVERN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_CYCLONIC
.byte ATTACK_NONE

; $0082: MONSTER_ZOMBONE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_POISON
.byte ATTACK_BIO

; $0083: MONSTER_DRAGON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_REVENGE
.byte ATTACK_BLIZZARD

; $0084: MONSTER_BRONTAUR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_FIRE_3
.byte ATTACK_METEOR

; $0085: MONSTER_ALLOSAURUS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_DOOM
.byte ATTACK_NONE

; $0086: MONSTER_CIRPIUS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BREAK
.byte ATTACK_NONE

; $0087: MONSTER_SPRINTER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_CYCLONIC
.byte ATTACK_NONE

; $0088: MONSTER_GOBBLER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SHIMSHAM
.byte ATTACK_NONE

; $0089: MONSTER_HARPIAI
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_AERO
.byte ATTACK_NONE

; $008a: MONSTER_GLOOMSHELL
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NET
.byte ATTACK_NONE

; $008b: MONSTER_DROP
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MUDDLE
.byte ATTACK_NONE

; $008c: MONSTER_MIND_CANDY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SLEEP
.byte ATTACK_NONE

; $008d: MONSTER_WEEDFEEDER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BSERK
.byte ATTACK_NONE

; $008e: MONSTER_LURIDAN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_LAND_SLIDE
.byte ATTACK_CAVE_IN

; $008f: MONSTER_TOE_CUTTER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SHRAPNEL
.byte ATTACK_NONE

; $0090: MONSTER_OVER_GRUNK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MUDDLE
.byte ATTACK_NONE

; $0091: MONSTER_EXORAY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_VIRITE
.byte ATTACK_NONE

; $0092: MONSTER_CRUSHER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_LIFESHAVER
.byte ATTACK_NONE

; $0093: MONSTER_UROBUROS
.byte ATTACK_BATTLE
.byte ATTACK_BIO
.byte ATTACK_QUAKE
.byte ATTACK_NONE

; $0094: MONSTER_PRIMORDITE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0095: MONSTER_SKY_CAP
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_TEK_LASER
.byte ATTACK_NONE

; $0096: MONSTER_CEPHALER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_STOP
.byte ATTACK_NONE

; $0097: MONSTER_MALIGA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_REMEDY
.byte ATTACK_NONE

; $0098: MONSTER_GIGAN_TOAD
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SLIMER
.byte ATTACK_NONE

; $0099: MONSTER_GECKOREX
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BREAK
.byte ATTACK_DREAD

; $009a: MONSTER_CLUCK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_QUAKE
.byte ATTACK_NONE

; $009b: MONSTER_LAND_WORM
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MAGNITUDE8
.byte ATTACK_LODE_STONE

; $009c: MONSTER_TEST_RIDER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_FLASH_RAIN
.byte ATTACK_NONE

; $009d: MONSTER_PLUTOARMOR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_TEK_LASER
.byte ATTACK_SHRAPNEL

; $009e: MONSTER_TOMB_THUMB
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_STEP_MINE
.byte ATTACK_NONE

; $009f: MONSTER_HEAVYARMOR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_TEK_LASER
.byte ATTACK_NONE

; $00a0: MONSTER_CHASER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_PLASMA
.byte ATTACK_DISCHORD

; $00a1: MONSTER_SCULLION
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SPECIAL
.byte ATTACK_SPECIAL

; $00a2: MONSTER_POPLIUM
.byte ATTACK_BATTLE
.byte ATTACK_SLOW
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00a3: MONSTER_INTANGIR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_PEP_UP
.byte ATTACK_NONE

; $00a4: MONSTER_MISFIT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_LIFESHAVER
.byte ATTACK_NONE

; $00a5: MONSTER_ELAND
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BIO
.byte ATTACK_POISON

; $00a6: MONSTER_ENUO
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_CLEANSWEEP
.byte ATTACK_AQUA_RAKE

; $00a7: MONSTER_DEEP_EYE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_DREAD
.byte ATTACK_NONE

; $00a8: MONSTER_GREASEMONK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_STEP_MINE
.byte ATTACK_NONE

; $00a9: MONSTER_NECKHUNTER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_IMP
.byte ATTACK_NONE

; $00aa: MONSTER_GRENADE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BLAZE
.byte ATTACK_FIRE_BALL

; $00ab: MONSTER_CRITIC
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_CONDEMNED
.byte ATTACK_NONE

; $00ac: MONSTER_PAN_DORA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_REVENGE
.byte ATTACK_NONE

; $00ad: MONSTER_SOULDANCER
.byte ATTACK_BATTLE
.byte ATTACK_DRAIN
.byte ATTACK_OSMOSE
.byte ATTACK_FIRE_2

; $00ae: MONSTER_GIGANTOS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_REVENGE
.byte ATTACK_NONE

; $00af: MONSTER_MAG_ROADER_2
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00b0: MONSTER_SPEK_TOR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_ACID_RAIN
.byte ATTACK_NONE

; $00b1: MONSTER_PARASITE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_GIGA_VOLT
.byte ATTACK_NONE

; $00b2: MONSTER_EARTHGUARD
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BIG_GUARD
.byte ATTACK_NONE

; $00b3: MONSTER_COELECITE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MAGNITUDE8
.byte ATTACK_NONE

; $00b4: MONSTER_ANEMONE
.byte ATTACK_BATTLE
.byte ATTACK_BOLT_3
.byte ATTACK_GIGA_VOLT
.byte ATTACK_NONE

; $00b5: MONSTER_HIPOCAMPUS
.byte ATTACK_BATTLE
.byte ATTACK_ACID_RAIN
.byte ATTACK_FLASH_RAIN
.byte ATTACK_NONE

; $00b6: MONSTER_SPECTRE
.byte ATTACK_BATTLE
.byte ATTACK_BOLT
.byte ATTACK_FIRE
.byte ATTACK_ICE

; $00b7: MONSTER_EVIL_OSCAR
.byte ATTACK_BATTLE
.byte ATTACK_POISON
.byte ATTACK_SNEEZE
.byte ATTACK_SOUR_MOUTH

; $00b8: MONSTER_SLURM
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MAGNITUDE8
.byte ATTACK_QUAKE

; $00b9: MONSTER_LATIMERIA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MAGNITUDE8
.byte ATTACK_NONE

; $00ba: MONSTER_STILLGOING
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00bb: MONSTER_ALLO_VER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SPECIAL
.byte ATTACK_SPECIAL

; $00bc: MONSTER_PHASE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BLOW_FISH
.byte ATTACK_NONE

; $00bd: MONSTER_OUTSIDER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_X_ZONE
.byte ATTACK_FLARE

; $00be: MONSTER_BARB_E
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MUDDLE
.byte ATTACK_DISPEL

; $00bf: MONSTER_PARASOUL
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_FLASH_RAIN
.byte ATTACK_EL_NINO

; $00c0: MONSTER_PM_STALKER
.byte ATTACK_BATTLE
.byte ATTACK_POISON
.byte ATTACK_DRAIN
.byte ATTACK_BIO

; $00c1: MONSTER_HEMOPHYTE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SHOCK_WAVE
.byte ATTACK_PEARL

; $00c2: MONSTER_SP_FORCES
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SAFE
.byte ATTACK_NONE

; $00c3: MONSTER_NOHRABBIT
.byte ATTACK_BATTLE
.byte ATTACK_CURE
.byte ATTACK_CURE_2
.byte ATTACK_REMEDY

; $00c4: MONSTER_WIZARD
.byte ATTACK_BATTLE
.byte ATTACK_RASP
.byte ATTACK_DEMI
.byte ATTACK_STOP

; $00c5: MONSTER_SCRAPPER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_ELF_FIRE
.byte ATTACK_NONE

; $00c6: MONSTER_CERITOPS
.byte ATTACK_BATTLE
.byte ATTACK_BOLT_3
.byte ATTACK_GIGA_VOLT
.byte ATTACK_NONE

; $00c7: MONSTER_COMMANDO
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SHELL
.byte ATTACK_NONE

; $00c8: MONSTER_OPINICUS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SLIDE
.byte ATTACK_SURGE

; $00c9: MONSTER_POPPERS
.byte ATTACK_BATTLE
.byte ATTACK_BREAK
.byte ATTACK_STONE
.byte ATTACK_NONE

; $00ca: MONSTER_LUNARIS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00cb: MONSTER_GARM
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_FIRE_2
.byte ATTACK_NONE

; $00cc: MONSTER_VINDR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_ACID_RAIN
.byte ATTACK_NONE

; $00cd: MONSTER_KIWOK
.byte ATTACK_BATTLE
.byte ATTACK_REMEDY
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00ce: MONSTER_NASTIDON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00cf: MONSTER_RINN
.byte ATTACK_BATTLE
.byte ATTACK_SLOW
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00d0: MONSTER_INSECARE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00d1: MONSTER_VERMIN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_BIO
.byte ATTACK_NONE

; $00d2: MONSTER_MANTODEA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_WIND_SLASH
.byte ATTACK_NONE

; $00d3: MONSTER_BOGY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00d4: MONSTER_PRUSSIAN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_STONE
.byte ATTACK_NONE

; $00d5: MONSTER_BLACK_DRGN
.byte ATTACK_BATTLE
.byte ATTACK_SAND_STORM
.byte ATTACK_DOOM
.byte ATTACK_BOLT_2

; $00d6: MONSTER_ADAMANCHYT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_ACID_RAIN
.byte ATTACK_NONE

; $00d7: MONSTER_DANTE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_L3_MUDDLE
.byte ATTACK_ICE_2

; $00d8: MONSTER_WIREY_DRGN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_CYCLONIC
.byte ATTACK_NONE

; $00d9: MONSTER_DUELLER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_MEGA_VOLT
.byte ATTACK_GIGA_VOLT

; $00da: MONSTER_PSYCHOT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_LIFESHAVER
.byte ATTACK_NONE

; $00db: MONSTER_MUUS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_PEP_UP
.byte ATTACK_NONE

; $00dc: MONSTER_KARKASS
.byte ATTACK_BATTLE
.byte ATTACK_BREAK
.byte ATTACK_BOLT_3
.byte ATTACK_FLARE

; $00dd: MONSTER_PUNISHER
.byte ATTACK_BATTLE
.byte ATTACK_NONE
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00de: MONSTER_BALLOON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_EXPLODER
.byte ATTACK_NONE

; $00df: MONSTER_GABBLDEGAK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_VANISH
.byte ATTACK_NONE

; $00e0: MONSTER_GTBEHEMOTH
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_METEOR
.byte ATTACK_FIRE_3

; $00e1: MONSTER_SCORPION
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00e2: MONSTER_CHAOS_DRGN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_DISASTER
.byte ATTACK_METEOR

; $00e3: MONSTER_SPIT_FIRE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_TEK_LASER
.byte ATTACK_SCHILLER

; $00e4: MONSTER_VECTAGOYLE
.byte ATTACK_BATTLE
.byte ATTACK_GIGA_VOLT
.byte ATTACK_AQUA_RAKE
.byte ATTACK_BLAZE

; $00e5: MONSTER_LICH
.byte ATTACK_BATTLE
.byte ATTACK_FIRE
.byte ATTACK_FIRE_2
.byte ATTACK_FIRE_3

; $00e6: MONSTER_OSPREY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SHIMSHAM
.byte ATTACK_NONE

; $00e7: MONSTER_MAG_ROADER_3
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00e8: MONSTER_BUG
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00e9: MONSTER_SEA_FLOWER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00ea: MONSTER_FORTIS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_FIRE_BALL
.byte ATTACK_SNOWBALL

; $00eb: MONSTER_ABOLISHER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_POISON
.byte ATTACK_NONE

; $00ec: MONSTER_AQUILA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_CYCLONIC
.byte ATTACK_SHIMSHAM

; $00ed: MONSTER_JUNK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_PEP_UP
.byte ATTACK_EXPLODER

; $00ee: MONSTER_MANDRAKE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_RAID
.byte ATTACK_NONE

; $00ef: MONSTER_1ST_CLASS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00f0: MONSTER_TAP_DANCER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SLOW_2
.byte ATTACK_HASTE2

; $00f1: MONSTER_NECROMANCR
.byte ATTACK_BATTLE
.byte ATTACK_X_ZONE
.byte ATTACK_DOOM
.byte ATTACK_FLARE

; $00f2: MONSTER_BORRAS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_SPECIAL
.byte ATTACK_SPECIAL

; $00f3: MONSTER_MAG_ROADER_4
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00f4: MONSTER_WILD_RAT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00f5: MONSTER_GOLD_BEAR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00f6: MONSTER_INNOC
.byte ATTACK_BATTLE
.byte ATTACK_PEARL_LORE
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00f7: MONSTER_TRIXTER
.byte ATTACK_BATTLE
.byte ATTACK_FIRE
.byte ATTACK_FIRE_2
.byte ATTACK_FIRE_3

; $00f8: MONSTER_RED_WOLF
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00f9: MONSTER_DIDALOS
.byte ATTACK_BATTLE
.byte ATTACK_FLARE
.byte ATTACK_FLARE_STAR
.byte ATTACK_BLASTER

; $00fa: MONSTER_WOOLLY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $00fb: MONSTER_VETERAN
.byte ATTACK_BATTLE
.byte ATTACK_DOOM
.byte ATTACK_X_ZONE
.byte ATTACK_ROULETTE

; $00fc: MONSTER_SKY_BASE
.byte ATTACK_BATTLE
.byte ATTACK_DOOM
.byte ATTACK_DOOM
.byte ATTACK_DOOM

; $00fd: MONSTER_IRONHITMAN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_DISCHORD
.byte ATTACK_TEK_LASER

; $00fe: MONSTER_IO
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_PLASMA
.byte ATTACK_BLASTER

; $00ff: MONSTER_PUGS
.byte ATTACK_BATTLE
.byte ATTACK_NONE
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0100: MONSTER_WHELK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0101: MONSTER_PRESENTER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0102: MONSTER_MEGA_ARMOR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_TEK_LASER
.byte ATTACK_NONE

; $0103: MONSTER_VARGAS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0104: MONSTER_TUNNELARMR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0105: MONSTER_PROMETHEUS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_S_CROSS
.byte ATTACK_N_CROSS

; $0106: MONSTER_GHOSTTRAIN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0107: MONSTER_DADALUMA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0108: MONSTER_SHIVA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0109: MONSTER_IFRIT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $010a: MONSTER_NUMBER_024
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $010b: MONSTER_NUMBER_128
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $010c: MONSTER_INFERNO
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $010d: MONSTER_CRANE_1
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $010e: MONSTER_CRANE_2
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $010f: MONSTER_UMARO_1
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0110: MONSTER_UMARO_2
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0111: MONSTER_GUARDIAN_VECTOR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0112: MONSTER_GUARDIAN_BOSS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_PLASMA
.byte ATTACK_NONE

; $0113: MONSTER_AIR_FORCE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0114: MONSTER_TRITOCH_INTRO
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0115: MONSTER_TRITOCH_MORPH
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0116: MONSTER_FLAMEEATER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0117: MONSTER_ATMAWEAPON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0118: MONSTER_NERAPA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0119: MONSTER_SRBEHEMOTH
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $011a: MONSTER_KEFKA_1
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $011b: MONSTER_TENTACLE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $011c: MONSTER_DULLAHAN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $011d: MONSTER_DOOM_GAZE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $011e: MONSTER_CHADARNOOK_1
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $011f: MONSTER_CURLEY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0120: MONSTER_LARRY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0121: MONSTER_MOE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0122: MONSTER_WREXSOUL
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0123: MONSTER_HIDON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0124: MONSTER_KATANASOUL
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0125: MONSTER_L30_MAGIC
.byte ATTACK_BATTLE
.byte ATTACK_BOLT_2
.byte ATTACK_OSMOSE
.byte ATTACK_RFLECT

; $0126: MONSTER_HIDONITE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0127: MONSTER_DOOM
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0128: MONSTER_GODDESS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0129: MONSTER_POLTRGEIST
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $012a: MONSTER_FINAL_KEFKA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $012b: MONSTER_L40_MAGIC
.byte ATTACK_BATTLE
.byte ATTACK_DRAIN
.byte ATTACK_MUTE
.byte ATTACK_VANISH

; $012c: MONSTER_ULTROS_RIVER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $012d: MONSTER_ULTROS_OPERA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $012e: MONSTER_ULTROS_MOUNTAIN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $012f: MONSTER_CHUPON_AIRSHIP
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0130: MONSTER_L20_MAGIC
.byte ATTACK_BATTLE
.byte ATTACK_QUARTR
.byte ATTACK_RASP
.byte ATTACK_SAFE

; $0131: MONSTER_SIEGFRIED_2
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0132: MONSTER_L10_MAGIC
.byte ATTACK_BATTLE
.byte ATTACK_BOLT
.byte ATTACK_SLOW
.byte ATTACK_HASTE

; $0133: MONSTER_L50_MAGIC
.byte ATTACK_BATTLE
.byte ATTACK_BIO
.byte ATTACK_BSERK
.byte ATTACK_HASTE2

; $0134: MONSTER_HEAD
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0135: MONSTER_WHELK_HEAD
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0136: MONSTER_COLOSSUS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0137: MONSTER_CZARDRAGON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0138: MONSTER_MASTER_PUG
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0139: MONSTER_L60_MAGIC
.byte ATTACK_BATTLE
.byte ATTACK_QUAKE
.byte ATTACK_SLOW_2
.byte ATTACK_REGEN

; $013a: MONSTER_MERCHANT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $013b: MONSTER_B_DAY_SUIT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $013c: MONSTER_TENTACLE_1
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $013d: MONSTER_TENTACLE_2
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $013e: MONSTER_TENTACLE_3
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $013f: MONSTER_RIGHTBLADE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0140: MONSTER_LEFT_BLADE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0141: MONSTER_ROUGH
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0142: MONSTER_STRIKER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0143: MONSTER_L70_MAGIC
.byte ATTACK_BATTLE
.byte ATTACK_FIRE_3
.byte ATTACK_ICE_3
.byte ATTACK_BOLT_3

; $0144: MONSTER_TRITOCH_BOSS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0145: MONSTER_LASER_GUN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0146: MONSTER_SPECK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0147: MONSTER_MISSILEBAY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0148: MONSTER_CHADARNOOK_2
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0149: MONSTER_ICE_DRAGON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $014a: MONSTER_KEFKA_NARSHE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $014b: MONSTER_STORM_DRGN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $014c: MONSTER_DIRT_DRGN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $014d: MONSTER_IPOOH
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $014e: MONSTER_LEADER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $014f: MONSTER_GRUNT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0150: MONSTER_GOLD_DRGN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0151: MONSTER_SKULL_DRGN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0152: MONSTER_BLUE_DRGN
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0153: MONSTER_RED_DRAGON
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0154: MONSTER_PIRANHA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0155: MONSTER_RIZOPAS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0156: MONSTER_SPECTER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0157: MONSTER_SHORT_ARM
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0158: MONSTER_LONG_ARM
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0159: MONSTER_FACE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $015a: MONSTER_TIGER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $015b: MONSTER_TOOLS
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $015c: MONSTER_MAGIC
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $015d: MONSTER_HIT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $015e: MONSTER_GIRL
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $015f: MONSTER_SLEEP
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0160: MONSTER_HIDONITE_1
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0161: MONSTER_HIDONITE_2
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0162: MONSTER_HIDONITE_3
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0163: MONSTER_L80_MAGIC
.byte ATTACK_BATTLE
.byte ATTACK_RFLECT
.byte ATTACK_CURE_3
.byte ATTACK_REMEDY

; $0164: MONSTER_L90_MAGIC
.byte ATTACK_BATTLE
.byte ATTACK_METEOR
.byte ATTACK_MERTON
.byte ATTACK_W_WIND

; $0165: MONSTER_PROTOARMOR
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_TEK_LASER
.byte ATTACK_SCHILLER

; $0166: MONSTER_MAGIMASTER
.byte ATTACK_BATTLE
.byte ATTACK_ULTIMA
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0167: MONSTER_SOULSAVER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0168: MONSTER_ULTROS_AIRSHIP
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0169: MONSTER_NAUGHTY
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $016a: MONSTER_PHUNBABA_1
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $016b: MONSTER_PHUNBABA_2
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $016c: MONSTER_PHUNBABA_3
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $016d: MONSTER_PHUNBABA_4
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $016e: MONSTER_TERRA_FLASHBACK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $016f: MONSTER_KEFKA_IMP_CAMP
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0170: MONSTER_CYAN_IMP_CAMP
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0171: MONSTER_ZONE_EATER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0172: MONSTER_GAU_VELDT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0173: MONSTER_KEFKA_VS_LEO
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0174: MONSTER_KEFKA_ESPER_GATE
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0175: MONSTER_OFFICER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0176: MONSTER_CADET
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0177: MONSTER_0177
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0178: MONSTER_0178
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $0179: MONSTER_SOLDIER_FLASHBACK
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $017a: MONSTER_KEFKA_VS_ESPER
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $017b: MONSTER_EVENT
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $017c: MONSTER_017C
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $017d: MONSTER_ATMA
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $017e: MONSTER_SHADOW_COLOSSEUM
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; $017f: MONSTER_COLOSSEUM
.byte ATTACK_BATTLE
.byte ATTACK_SPECIAL
.byte ATTACK_NONE
.byte ATTACK_NONE

; ------------------------------------------------------------------------------
