; ------------------------------------------------------------------------------

.mac make_monster_sketch attack1, attack2
        .byte ATTACK::attack1, ATTACK::attack2
.endmac

; ------------------------------------------------------------------------------

; cf/4300
MonsterSketch:
        make_monster_sketch BATTLE, BATTLE              ; GUARD
        make_monster_sketch SCAN, BATTLE                ; SOLDIER
        make_monster_sketch SPECIAL, BATTLE             ; TEMPLAR
        make_monster_sketch FIRE_SKEAN, WATER_EDGE      ; NINJA
        make_monster_sketch FLARE, DOOM                 ; SAMURAI
        make_monster_sketch BIO, PEARL                  ; OROG
        make_monster_sketch SPECIAL, BATTLE             ; MAG_ROADER_1
        make_monster_sketch SPECIAL, WIND_SLASH         ; RETAINER
        make_monster_sketch DRAIN, BATTLE               ; HAZER
        make_monster_sketch MUTE, CURE_2                ; DAHLING
        make_monster_sketch SPECIAL, BOLT_3             ; RAIN_MAN
        make_monster_sketch SPECIAL, BATTLE             ; BRAWLER
        make_monster_sketch SPECIAL, L3_MUDDLE          ; APOKRYPHOS
        make_monster_sketch L5_DOOM, CLEANSWEEP         ; DARK_FORCE
        make_monster_sketch QUARTR, DEMI                ; WHISPER
        make_monster_sketch DREAD, BATTLE               ; OVER_MIND
        make_monster_sketch SPECIAL, BATTLE             ; OSTEOSAUR
        make_monster_sketch FIRE, BATTLE                ; COMMANDER
        make_monster_sketch SPECIAL, SNARE              ; RHODOX
        make_monster_sketch SPECIAL, BATTLE             ; WERE_RAT
        make_monster_sketch SPECIAL, FIRE_2             ; URSUS
        make_monster_sketch MEGA_VOLT, GIGA_VOLT        ; RHINOTAUR
        make_monster_sketch SPECIAL, SLIDE              ; STEROIDITE
        make_monster_sketch SPECIAL, BATTLE             ; LEAFER
        make_monster_sketch SPECIAL, BLASTER            ; STRAY_CAT
        make_monster_sketch SPECIAL, BATTLE             ; LOBO
        make_monster_sketch SPECIAL, BATTLE             ; DOBERMAN
        make_monster_sketch SPECIAL, BLIZZARD           ; VOMAMMOTH
        make_monster_sketch SPECIAL, BATTLE             ; FIDOR
        make_monster_sketch SPECIAL, ABSOLUTE0          ; BASKERVOR
        make_monster_sketch SPECIAL, AQUA_RAKE          ; SURIANDER
        make_monster_sketch SPECIAL, AQUA_RAKE          ; CHIMERA
        make_monster_sketch SPECIAL, METEOR             ; BEHEMOTH
        make_monster_sketch SPECIAL, STEP_MINE          ; MESOSAUR
        make_monster_sketch SPECIAL, FIRE_BALL          ; PTERODON
        make_monster_sketch SPECIAL, SAND_STORM         ; FOSSILFANG
        make_monster_sketch FLARE, PEARL                ; WHITE_DRGN
        make_monster_sketch FALLEN_ONE, N_CROSS         ; DOOM_DRGN
        make_monster_sketch SPECIAL, STEP_MINE          ; BRACHOSAUR
        make_monster_sketch SPECIAL, AERO               ; TYRANOSAUR
        make_monster_sketch SPECIAL, BATTLE             ; DARK_WIND
        make_monster_sketch SPECIAL, BATTLE             ; BEAKOR
        make_monster_sketch SPECIAL, SHIMSHAM           ; VULTURE
        make_monster_sketch SPECIAL, CYCLONIC           ; HARPY
        make_monster_sketch SPECIAL, NET                ; HERMITCRAB
        make_monster_sketch L5_DOOM, L3_MUDDLE          ; TRAPPER
        make_monster_sketch SPECIAL, BATTLE             ; HORNET
        make_monster_sketch SPECIAL, BATTLE             ; CRASSHOPPR
        make_monster_sketch SPECIAL, MEGA_VOLT          ; DELTA_BUG
        make_monster_sketch SPECIAL, LODE_STONE         ; GILOMANTIS
        make_monster_sketch SPECIAL, BATTLE             ; TRILIUM
        make_monster_sketch SPECIAL, CHARM              ; NIGHTSHADE
        make_monster_sketch SPECIAL, LIFESHAVER         ; TUMBLEWEED
        make_monster_sketch SPECIAL, BIO                ; BLOOMPIRE
        make_monster_sketch SPECIAL, BATTLE             ; TRILOBITER
        make_monster_sketch BATTLE, BATTLE              ; SIEGFRIED_1
        make_monster_sketch SPECIAL, BATTLE             ; NAUTILOID
        make_monster_sketch SPECIAL, BATTLE             ; EXOCITE
        make_monster_sketch SPECIAL, AQUA_RAKE          ; ANGUIFORM
        make_monster_sketch SPECIAL, SLIMER             ; REACH_FROG
        make_monster_sketch IMP, REMEDY                 ; LIZARD
        make_monster_sketch SPECIAL, QUAKE              ; CHICKENLIP
        make_monster_sketch SPECIAL, SAND_STORM         ; HOOVER
        make_monster_sketch SPECIAL, VIRITE             ; RIDER
        make_monster_sketch BATTLE, BATTLE              ; CHUPON_COLOSSEUM
        make_monster_sketch IMP, ROULETTE               ; PIPSQUEAK
        make_monster_sketch TEK_LASER, BATTLE           ; M_TEKARMOR
        make_monster_sketch SPECIAL, TEK_LASER          ; SKY_ARMOR
        make_monster_sketch LAUNCHER, TEK_LASER         ; TELSTAR
        make_monster_sketch SPECIAL, MEGAZERK           ; LETHAL_WPN
        make_monster_sketch SLOW, BATTLE                ; VAPORITE
        make_monster_sketch SPECIAL, SLIMER             ; FLAN
        make_monster_sketch SPECIAL, LIFESHAVER         ; ING
        make_monster_sketch SPECIAL, POISON             ; HUMPTY
        make_monster_sketch SPECIAL, BLOW_FISH          ; BRAINPAN
        make_monster_sketch SPECIAL, SLIMER             ; CRULLER
        make_monster_sketch SPECIAL, BLOW_FISH          ; CACTROT
        make_monster_sketch SPECIAL, FLARE              ; REPO_MAN
        make_monster_sketch SPECIAL, FIRE_WALL          ; HARVESTER
        make_monster_sketch EXPLODER, BLAZE             ; BOMB
        make_monster_sketch SPECIAL, LULLABY            ; STILL_LIFE
        make_monster_sketch SPECIAL, METEOR             ; BOXED_SET
        make_monster_sketch FIRE_2, ICE_2               ; SLAMDANCER
        make_monster_sketch SPECIAL, MAGNITUDE8         ; HADESGIGAS
        make_monster_sketch SPECIAL, BREAK              ; PUG
        make_monster_sketch REMEDY, CURE_3              ; MAGIC_URN
        make_monster_sketch BATTLE, DISASTER            ; MOVER
        make_monster_sketch SPECIAL, DISCHORD           ; FIGALIZ
        make_monster_sketch SPECIAL, BATTLE             ; BUFFALAX
        make_monster_sketch SPECIAL, GIGA_VOLT          ; ASPIK
        make_monster_sketch FIRE, X_ZONE                ; GHOST
        make_monster_sketch SPECIAL, STEP_MINE          ; CRAWLER
        make_monster_sketch SPECIAL, BATTLE             ; SAND_RAY
        make_monster_sketch SPECIAL, BATTLE             ; ARENEID
        make_monster_sketch SPECIAL, AQUA_RAKE          ; ACTANEON
        make_monster_sketch SPECIAL, SAND_STORM         ; SAND_HORSE
        make_monster_sketch SPECIAL, FIRE_3             ; DARK_SIDE
        make_monster_sketch SPECIAL, SOUR_MOUTH         ; MAD_OSCAR
        make_monster_sketch SPECIAL, BATTLE             ; CRAWLY
        make_monster_sketch SPECIAL, BATTLE             ; BLEARY
        make_monster_sketch SPECIAL, BATTLE             ; MARSHAL
        make_monster_sketch SPECIAL, BATTLE             ; TROOPER
        make_monster_sketch SPECIAL, CURE_2             ; GENERAL
        make_monster_sketch SPECIAL, WIND_SLASH         ; COVERT
        make_monster_sketch BATTLE, METEOR              ; OGOR
        make_monster_sketch SPECIAL, PEARL              ; WARLOCK
        make_monster_sketch FLARE, PEARL                ; MADAM
        make_monster_sketch SPECIAL, BOLT_2             ; JOKER
        make_monster_sketch SPECIAL, STONE              ; IRON_FIST
        make_monster_sketch FIRE_3, BOLT_3              ; GOBLIN
        make_monster_sketch SPECIAL, SPECIAL            ; APPARITE
        make_monster_sketch SPECIAL, FLARE              ; POWERDEMON
        make_monster_sketch SPECIAL, DOOM               ; DISPLAYER
        make_monster_sketch SPECIAL, BATTLE             ; VECTOR_PUP
        make_monster_sketch SPECIAL, PEARL_WIND         ; PEEPERS
        make_monster_sketch SPECIAL, BATTLE             ; SEWER_RAT
        make_monster_sketch SPECIAL, SHIMSHAM           ; SLATTER
        make_monster_sketch SPECIAL, LIFE_3             ; RHINOX
        make_monster_sketch SPECIAL, BATTLE             ; RHOBITE
        make_monster_sketch SPECIAL, BLASTER            ; WILD_CAT
        make_monster_sketch SPECIAL, BATTLE             ; RED_FANG
        make_monster_sketch SPECIAL, BATTLE             ; BOUNTY_MAN
        make_monster_sketch SPECIAL, BLIZZARD           ; TUSKER
        make_monster_sketch SPECIAL, BATTLE             ; RALPH
        make_monster_sketch SPECIAL, BATTLE             ; CHITONID
        make_monster_sketch SPECIAL, BATTLE             ; WART_PUCK
        make_monster_sketch EL_NINO, SURGE              ; RHYOS
        make_monster_sketch SPECIAL, FIRE_3             ; SRBEHEMOTH_UNDEAD
        make_monster_sketch SPECIAL, PEARL_WIND         ; VECTAUR
        make_monster_sketch SPECIAL, CYCLONIC           ; WYVERN
        make_monster_sketch SPECIAL, BOLT_3             ; ZOMBONE
        make_monster_sketch SPECIAL, REVENGE            ; DRAGON
        make_monster_sketch SPECIAL, FIRE_3             ; BRONTAUR
        make_monster_sketch SPECIAL, DOOM               ; ALLOSAURUS
        make_monster_sketch SPECIAL, BATTLE             ; CIRPIUS
        make_monster_sketch SPECIAL, AERO               ; SPRINTER
        make_monster_sketch SPECIAL, SHIMSHAM           ; GOBBLER
        make_monster_sketch SPECIAL, AERO               ; HARPIAI
        make_monster_sketch SPECIAL, NET                ; GLOOMSHELL
        make_monster_sketch SPECIAL, MUDDLE             ; DROP
        make_monster_sketch SPECIAL, BATTLE             ; MIND_CANDY
        make_monster_sketch SPECIAL, LIFESHAVER         ; WEEDFEEDER
        make_monster_sketch SPECIAL, LAND_SLIDE         ; LURIDAN
        make_monster_sketch SPECIAL, SHRAPNEL           ; TOE_CUTTER
        make_monster_sketch SPECIAL, POISON             ; OVER_GRUNK
        make_monster_sketch SPECIAL, VIRITE             ; EXORAY
        make_monster_sketch SPECIAL, LIFESHAVER         ; CRUSHER
        make_monster_sketch BIO, QUAKE                  ; UROBUROS
        make_monster_sketch SPECIAL, BATTLE             ; PRIMORDITE
        make_monster_sketch SPECIAL, ATOMIC_RAY         ; SKY_CAP
        make_monster_sketch SPECIAL, BATTLE             ; CEPHALER
        make_monster_sketch SPECIAL, BATTLE             ; MALIGA
        make_monster_sketch SPECIAL, SLIMER             ; GIGAN_TOAD
        make_monster_sketch SPECIAL, BREAK              ; GECKOREX
        make_monster_sketch SPECIAL, QUAKE              ; CLUCK
        make_monster_sketch SPECIAL, MAGNITUDE8         ; LAND_WORM
        make_monster_sketch SPECIAL, FLASH_RAIN         ; TEST_RIDER
        make_monster_sketch SPECIAL, TEK_LASER          ; PLUTOARMOR
        make_monster_sketch SPECIAL, STEP_MINE          ; TOMB_THUMB
        make_monster_sketch SPECIAL, TEK_LASER          ; HEAVYARMOR
        make_monster_sketch SPECIAL, PLASMA             ; CHASER
        make_monster_sketch SPECIAL, EXPLODER           ; SCULLION
        make_monster_sketch SLOW, BATTLE                ; POPLIUM
        make_monster_sketch SPECIAL, STEP_MINE          ; INTANGIR
        make_monster_sketch SPECIAL, LIFESHAVER         ; MISFIT
        make_monster_sketch SPECIAL, BIO                ; ELAND
        make_monster_sketch SPECIAL, CLEANSWEEP         ; ENUO
        make_monster_sketch SPECIAL, DREAD              ; DEEP_EYE
        make_monster_sketch SPECIAL, SPECIAL            ; GREASEMONK
        make_monster_sketch SPECIAL, IMP                ; NECKHUNTER
        make_monster_sketch SPECIAL, BLAZE              ; GRENADE
        make_monster_sketch SPECIAL, CONDEMNED          ; CRITIC
        make_monster_sketch SPECIAL, REVENGE            ; PAN_DORA
        make_monster_sketch DRAIN, OSMOSE               ; SOULDANCER
        make_monster_sketch SPECIAL, BATTLE             ; GIGANTOS
        make_monster_sketch SPECIAL, BATTLE             ; MAG_ROADER_2
        make_monster_sketch SPECIAL, BLASTER            ; SPEK_TOR
        make_monster_sketch SPECIAL, GIGA_VOLT          ; PARASITE
        make_monster_sketch SPECIAL, BIG_GUARD          ; EARTHGUARD
        make_monster_sketch SPECIAL, MAGNITUDE8         ; COELECITE
        make_monster_sketch IMP, GIGA_VOLT              ; ANEMONE
        make_monster_sketch ACID_RAIN, FLASH_RAIN       ; HIPOCAMPUS
        make_monster_sketch BOLT, FIRE                  ; SPECTRE
        make_monster_sketch POISON, SOUR_MOUTH          ; EVIL_OSCAR
        make_monster_sketch SPECIAL, BATTLE             ; SLURM
        make_monster_sketch SPECIAL, MAGNITUDE8         ; LATIMERIA
        make_monster_sketch SPECIAL, BATTLE             ; STILLGOING
        make_monster_sketch SPECIAL, SPECIAL            ; ALLO_VER
        make_monster_sketch SPECIAL, BLOW_FISH          ; PHASE
        make_monster_sketch SPECIAL, BATTLE             ; OUTSIDER
        make_monster_sketch SPECIAL, LOVE_TOKEN         ; BARB_E
        make_monster_sketch SPECIAL, FLASH_RAIN         ; PARASOUL
        make_monster_sketch POISON, DRAIN               ; PM_STALKER
        make_monster_sketch SPECIAL, SHOCK_WAVE         ; HEMOPHYTE
        make_monster_sketch SPECIAL, BATTLE             ; SP_FORCES
        make_monster_sketch CURE, CURE_2                ; NOHRABBIT
        make_monster_sketch RASP, DEMI                  ; WIZARD
        make_monster_sketch SPECIAL, ELF_FIRE           ; SCRAPPER
        make_monster_sketch IMP, GIGA_VOLT              ; CERITOPS
        make_monster_sketch SPECIAL, BATTLE             ; COMMANDO
        make_monster_sketch SPECIAL, SLIDE              ; OPINICUS
        make_monster_sketch IMP, STONE                  ; POPPERS
        make_monster_sketch SPECIAL, BATTLE             ; LUNARIS
        make_monster_sketch SPECIAL, ICE_3              ; GARM
        make_monster_sketch SPECIAL, ACID_RAIN          ; VINDR
        make_monster_sketch IMP, CYCLONIC               ; KIWOK
        make_monster_sketch SPECIAL, BATTLE             ; NASTIDON
        make_monster_sketch SLOW, BATTLE                ; RINN
        make_monster_sketch SPECIAL, BATTLE             ; INSECARE
        make_monster_sketch SPECIAL, BIO                ; VERMIN
        make_monster_sketch SPECIAL, WIND_SLASH         ; MANTODEA
        make_monster_sketch SPECIAL, BATTLE             ; BOGY
        make_monster_sketch SPECIAL, BATTLE             ; PRUSSIAN
        make_monster_sketch SAND_STORM, FALLEN_ONE      ; BLACK_DRGN
        make_monster_sketch SPECIAL, BLASTER            ; ADAMANCHYT
        make_monster_sketch SPECIAL, L3_MUDDLE          ; DANTE
        make_monster_sketch SPECIAL, CYCLONIC           ; WIREY_DRGN
        make_monster_sketch SPECIAL, GIGA_VOLT          ; DUELLER
        make_monster_sketch SPECIAL, LIFESHAVER         ; PSYCHOT
        make_monster_sketch SPECIAL, PEP_UP             ; MUUS
        make_monster_sketch BREAK, BOLT_3               ; KARKASS
        make_monster_sketch BATTLE, BATTLE              ; PUNISHER
        make_monster_sketch SPECIAL, EXPLODER           ; BALLOON
        make_monster_sketch SPECIAL, VANISH             ; GABBLDEGAK
        make_monster_sketch SPECIAL, METEOR             ; GTBEHEMOTH
        make_monster_sketch SPECIAL, BATTLE             ; SCORPION
        make_monster_sketch SPECIAL, DISASTER           ; CHAOS_DRGN
        make_monster_sketch SPECIAL, TEK_LASER          ; SPIT_FIRE
        make_monster_sketch GIGA_VOLT, AQUA_RAKE        ; VECTAGOYLE
        make_monster_sketch FIRE, FIRE_2                ; LICH
        make_monster_sketch SPECIAL, SHIMSHAM           ; OSPREY
        make_monster_sketch SPECIAL, BATTLE             ; MAG_ROADER_3
        make_monster_sketch SPECIAL, BATTLE             ; BUG
        make_monster_sketch SPECIAL, BATTLE             ; SEA_FLOWER
        make_monster_sketch SPECIAL, SHRAPNEL           ; FORTIS
        make_monster_sketch SPECIAL, POISON             ; ABOLISHER
        make_monster_sketch SPECIAL, CYCLONIC           ; AQUILA
        make_monster_sketch SPECIAL, BOLT_3             ; JUNK
        make_monster_sketch SPECIAL, RAID               ; MANDRAKE
        make_monster_sketch SPECIAL, BATTLE             ; 1ST_CLASS
        make_monster_sketch SPECIAL, SLOW_2             ; TAP_DANCER
        make_monster_sketch X_ZONE, DOOM                ; NECROMANCR
        make_monster_sketch SPECIAL, SPECIAL            ; BORRAS
        make_monster_sketch SPECIAL, BATTLE             ; MAG_ROADER_4
        make_monster_sketch SPECIAL, BATTLE             ; WILD_RAT
        make_monster_sketch SPECIAL, BATTLE             ; GOLD_BEAR
        make_monster_sketch PEARL_LORE, BATTLE          ; INNOC
        make_monster_sketch FIRE, FIRE_2                ; TRIXTER
        make_monster_sketch SPECIAL, REVENGE            ; RED_WOLF
        make_monster_sketch SPECIAL, QUAKE              ; DIDALOS
        make_monster_sketch SPECIAL, W_WIND             ; WOOLLY
        make_monster_sketch ROULETTE, CONDEMNED         ; VETERAN
        make_monster_sketch DOOM, GIGA_VOLT             ; SKY_BASE
        make_monster_sketch SPECIAL, DISCHORD           ; IRONHITMAN
        make_monster_sketch SPECIAL, PLASMA             ; IO
        make_monster_sketch BATTLE, BATTLE              ; PUGS
        make_monster_sketch SPECIAL, BATTLE             ; WHELK
        make_monster_sketch SPECIAL, BATTLE             ; PRESENTER
        make_monster_sketch SPECIAL, TEK_LASER          ; MEGA_ARMOR
        make_monster_sketch SPECIAL, BATTLE             ; VARGAS
        make_monster_sketch SPECIAL, BATTLE             ; TUNNELARMR
        make_monster_sketch SPECIAL, S_CROSS            ; PROMETHEUS
        make_monster_sketch SPECIAL, BATTLE             ; GHOSTTRAIN
        make_monster_sketch SPECIAL, BATTLE             ; DADALUMA
        make_monster_sketch SPECIAL, BATTLE             ; SHIVA
        make_monster_sketch SPECIAL, BATTLE             ; IFRIT
        make_monster_sketch SPECIAL, BATTLE             ; NUMBER_024
        make_monster_sketch SPECIAL, BATTLE             ; NUMBER_128
        make_monster_sketch SPECIAL, BATTLE             ; INFERNO
        make_monster_sketch SPECIAL, BATTLE             ; CRANE_1
        make_monster_sketch SPECIAL, BATTLE             ; CRANE_2
        make_monster_sketch SPECIAL, BATTLE             ; UMARO_1
        make_monster_sketch SPECIAL, BATTLE             ; UMARO_2
        make_monster_sketch SPECIAL, BATTLE             ; GUARDIAN_VECTOR
        make_monster_sketch SPECIAL, BIG_GUARD          ; GUARDIAN_BOSS
        make_monster_sketch SPECIAL, BATTLE             ; AIR_FORCE
        make_monster_sketch SPECIAL, BATTLE             ; TRITOCH_INTRO
        make_monster_sketch SPECIAL, BATTLE             ; TRITOCH_MORPH
        make_monster_sketch SPECIAL, BATTLE             ; FLAMEEATER
        make_monster_sketch SPECIAL, BATTLE             ; ATMAWEAPON
        make_monster_sketch SPECIAL, BATTLE             ; NERAPA
        make_monster_sketch SPECIAL, BATTLE             ; SRBEHEMOTH
        make_monster_sketch SPECIAL, BATTLE             ; KEFKA_1
        make_monster_sketch SPECIAL, BATTLE             ; TENTACLE
        make_monster_sketch SPECIAL, BATTLE             ; DULLAHAN
        make_monster_sketch SPECIAL, BATTLE             ; DOOM_GAZE
        make_monster_sketch SPECIAL, BATTLE             ; CHADARNOOK_1
        make_monster_sketch SPECIAL, BATTLE             ; CURLEY
        make_monster_sketch SPECIAL, BATTLE             ; LARRY
        make_monster_sketch SPECIAL, BATTLE             ; MOE
        make_monster_sketch SPECIAL, BATTLE             ; WREXSOUL
        make_monster_sketch SPECIAL, BATTLE             ; HIDON
        make_monster_sketch SPECIAL, BATTLE             ; KATANASOUL
        make_monster_sketch BOLT_2, OSMOSE              ; L30_MAGIC
        make_monster_sketch SPECIAL, BATTLE             ; HIDONITE
        make_monster_sketch SPECIAL, BATTLE             ; DOOM
        make_monster_sketch SPECIAL, BATTLE             ; GODDESS
        make_monster_sketch SPECIAL, BATTLE             ; POLTRGEIST
        make_monster_sketch SPECIAL, ULTIMA             ; FINAL_KEFKA
        make_monster_sketch DRAIN, MUTE                 ; L40_MAGIC
        make_monster_sketch SPECIAL, BATTLE             ; ULTROS_RIVER
        make_monster_sketch SPECIAL, BATTLE             ; ULTROS_OPERA
        make_monster_sketch TENTACLE, TENTACLE          ; ULTROS_MOUNTAIN
        make_monster_sketch SPECIAL, BATTLE             ; CHUPON_AIRSHIP
        make_monster_sketch QUARTR, RASP                ; L20_MAGIC
        make_monster_sketch SPECIAL, BATTLE             ; SIEGFRIED_2
        make_monster_sketch BOLT, SLOW                  ; L10_MAGIC
        make_monster_sketch BIO, BSERK                  ; L50_MAGIC
        make_monster_sketch SPECIAL, BATTLE             ; HEAD
        make_monster_sketch SPECIAL, BATTLE             ; WHELK_HEAD
        make_monster_sketch SPECIAL, BATTLE             ; COLOSSUS
        make_monster_sketch SPECIAL, BATTLE             ; CZARDRAGON
        make_monster_sketch SPECIAL, BATTLE             ; MASTER_PUG
        make_monster_sketch QUAKE, SLOW_2               ; L60_MAGIC
        make_monster_sketch SPECIAL, BATTLE             ; MERCHANT
        make_monster_sketch SPECIAL, BATTLE             ; B_DAY_SUIT
        make_monster_sketch SPECIAL, BATTLE             ; TENTACLE_1
        make_monster_sketch SPECIAL, BATTLE             ; TENTACLE_2
        make_monster_sketch SPECIAL, BATTLE             ; TENTACLE_3
        make_monster_sketch SPECIAL, BATTLE             ; RIGHTBLADE
        make_monster_sketch SPECIAL, BATTLE             ; LEFT_BLADE
        make_monster_sketch SPECIAL, BATTLE             ; ROUGH
        make_monster_sketch SPECIAL, BATTLE             ; STRIKER
        make_monster_sketch FIRE_3, ICE_3               ; L70_MAGIC
        make_monster_sketch SPECIAL, BATTLE             ; TRITOCH_BOSS
        make_monster_sketch SPECIAL, BATTLE             ; LASER_GUN
        make_monster_sketch SPECIAL, BATTLE             ; SPECK
        make_monster_sketch SPECIAL, BATTLE             ; MISSILEBAY
        make_monster_sketch SPECIAL, BATTLE             ; CHADARNOOK_2
        make_monster_sketch FIRE_3, ICE_3               ; ICE_DRAGON
        make_monster_sketch SPECIAL, BATTLE             ; KEFKA_NARSHE
        make_monster_sketch PEARL_WIND, AERO            ; STORM_DRGN
        make_monster_sketch MAGNITUDE8, BOLT_3          ; DIRT_DRGN
        make_monster_sketch SPECIAL, BATTLE             ; IPOOH
        make_monster_sketch SPECIAL, BATTLE             ; LEADER
        make_monster_sketch SPECIAL, BATTLE             ; GRUNT
        make_monster_sketch ICE_3, BOLT_3               ; GOLD_DRGN
        make_monster_sketch RASP, BATTLE                ; SKULL_DRGN
        make_monster_sketch BLASTER, ICE_3              ; BLUE_DRGN
        make_monster_sketch PEARL_LORE, FIRE_3          ; RED_DRAGON
        make_monster_sketch SPECIAL, BATTLE             ; PIRANHA
        make_monster_sketch SPECIAL, BATTLE             ; RIZOPAS
        make_monster_sketch SPECIAL, BATTLE             ; SPECTER
        make_monster_sketch SPECIAL, BATTLE             ; SHORT_ARM
        make_monster_sketch SPECIAL, BATTLE             ; LONG_ARM
        make_monster_sketch SPECIAL, BATTLE             ; FACE
        make_monster_sketch SPECIAL, BATTLE             ; TIGER
        make_monster_sketch SPECIAL, BATTLE             ; TOOLS
        make_monster_sketch SPECIAL, BATTLE             ; MAGIC
        make_monster_sketch SPECIAL, BATTLE             ; HIT
        make_monster_sketch SPECIAL, BATTLE             ; GIRL
        make_monster_sketch SPECIAL, BATTLE             ; SLEEP
        make_monster_sketch SPECIAL, BATTLE             ; HIDONITE_1
        make_monster_sketch SPECIAL, BATTLE             ; HIDONITE_2
        make_monster_sketch SPECIAL, BATTLE             ; HIDONITE_3
        make_monster_sketch RFLECT, CURE_3              ; L80_MAGIC
        make_monster_sketch METEOR, MERTON              ; L90_MAGIC
        make_monster_sketch SPECIAL, TEK_LASER          ; PROTOARMOR
        make_monster_sketch BATTLE, BATTLE              ; MAGIMASTER
        make_monster_sketch SPECIAL, BATTLE             ; SOULSAVER
        make_monster_sketch SPECIAL, BATTLE             ; ULTROS_AIRSHIP
        make_monster_sketch SPECIAL, BATTLE             ; NAUGHTY
        make_monster_sketch SPECIAL, BATTLE             ; PHUNBABA_1
        make_monster_sketch SPECIAL, BATTLE             ; PHUNBABA_2
        make_monster_sketch SPECIAL, BATTLE             ; PHUNBABA_3
        make_monster_sketch SPECIAL, BATTLE             ; PHUNBABA_4
        make_monster_sketch SPECIAL, BATTLE             ; TERRA_FLASHBACK
        make_monster_sketch SPECIAL, BATTLE             ; KEFKA_IMP_CAMP
        make_monster_sketch SPECIAL, BATTLE             ; CYAN_IMP_CAMP
        make_monster_sketch SPECIAL, BATTLE             ; ZONE_EATER
        make_monster_sketch SPECIAL, BATTLE             ; GAU_VELDT
        make_monster_sketch SPECIAL, BATTLE             ; KEFKA_VS_LEO
        make_monster_sketch SPECIAL, BATTLE             ; KEFKA_ESPER_GATE
        make_monster_sketch SPECIAL, BATTLE             ; OFFICER
        make_monster_sketch SPECIAL, BATTLE             ; CADET
        make_monster_sketch SPECIAL, BATTLE             ; 0177
        make_monster_sketch SPECIAL, BATTLE             ; 0178
        make_monster_sketch SPECIAL, BATTLE             ; SOLDIER_FLASHBACK
        make_monster_sketch SPECIAL, BATTLE             ; KEFKA_VS_ESPER
        make_monster_sketch SPECIAL, BATTLE             ; EVENT
        make_monster_sketch SPECIAL, BATTLE             ; 017C
        make_monster_sketch SPECIAL, BATTLE             ; ATMA
        make_monster_sketch SPECIAL, BATTLE             ; SHADOW_COLOSSEUM
        make_monster_sketch SPECIAL, BATTLE             ; COLOSSEUM

; ------------------------------------------------------------------------------
