.list off
.ifndef BLITZ_CODE_INC
BLITZ_CODE_INC = 1

.global BlitzCode

BLITZ_CODE_ARRAY_LENGTH                 = 8
BLITZ_CODE_SIZE                         = 12

BLITZ_CODE_NONE                         = 0
BLITZ_CODE_A_BUTTON                     = 1
BLITZ_CODE_B_BUTTON                     = 2
BLITZ_CODE_X_BUTTON                     = 3
BLITZ_CODE_Y_BUTTON                     = 4
BLITZ_CODE_L_BUTTON                     = 5
BLITZ_CODE_R_BUTTON                     = 6
BLITZ_CODE_DOWN_LEFT                    = 7
BLITZ_CODE_DOWN                         = 8
BLITZ_CODE_DOWN_RIGHT                   = 9
BLITZ_CODE_RIGHT                        = 10
BLITZ_CODE_UP_RIGHT                     = 11
BLITZ_CODE_UP                           = 12
BLITZ_CODE_UP_LEFT                      = 13
BLITZ_CODE_LEFT                         = 14

.endif
.list on
