.list off
.ifndef MAP_PAL_INC
MAP_PAL_INC = 1

.global MapPal

MAP_PAL_FIGARO                          = $00  ; 0
MAP_PAL_VILLAGE_EXT_1                   = $01  ; 1
MAP_PAL_DOMA                            = $02  ; 2
MAP_PAL_TOWN_EXT_1                      = $03  ; 3
MAP_PAL_DOCKS                           = $04  ; 4
MAP_PAL_CAVES_1                         = $05  ; 5
MAP_PAL_CASTLE_INT                      = $06  ; 6
MAP_PAL_RIVER                           = $07  ; 7
MAP_PAL_IMP_CAMP                        = $08  ; 8
MAP_PAL_MOUNTAINS_INT                   = $09  ; 9
MAP_PAL_TOWN_INT_1                      = $0a  ; 10
MAP_PAL_OPERA_1                         = $0b  ; 11
MAP_PAL_NARSHE_EXT                      = $0c  ; 12
MAP_PAL_SNOWFIELDS                      = $0d  ; 13
MAP_PAL_TRAIN_EXT                       = $0e  ; 14
MAP_PAL_TRAIN_INT                       = $0f  ; 15
MAP_PAL_ZOZO_EXT_1                      = $10  ; 16
MAP_PAL_VECTOR                          = $11  ; 17
MAP_PAL_CAVES_2                         = $12  ; 18
MAP_PAL_FLOATING_ISLAND                 = $13  ; 19
MAP_PAL_ZOZO_INT                        = $14  ; 20
MAP_PAL_CAVES_3                         = $15  ; 21
MAP_PAL_VILLAGE_EXT_3                   = $16  ; 22
MAP_PAL_MOUNTAINS_EXT_1                 = $17  ; 23
MAP_PAL_MAGITEK_FACTORY                 = $18  ; 24
MAP_PAL_AIRSHIP_EXT_1                   = $19  ; 25
MAP_PAL_AIRSHIP_INT                     = $1a  ; 26
MAP_PAL_CYANS_DREAM                     = $1b  ; 27
MAP_PAL_FOREST                          = $1c  ; 28
MAP_PAL_IMP_CASTLE_EXT                  = $1d  ; 29
MAP_PAL_BEACH                           = $1e  ; 30
MAP_PAL_IMP_CASTLE_INT                  = $1f  ; 31
MAP_PAL_CAVES_4                         = $20  ; 32
MAP_PAL_SEALED_GATE                     = $21  ; 33
MAP_PAL_KEFKAS_TOWER_1                  = $22  ; 34
MAP_PAL_BURNING_BUILDING                = $23  ; 35
MAP_PAL_TOWN_INT_2                      = $24  ; 36
MAP_PAL_NARSHE_INT                      = $25  ; 37
MAP_PAL_VILLAGE_EXT_2                   = $26  ; 38
MAP_PAL_OPERA_2                         = $27  ; 39
MAP_PAL_DARILLS_TOMB_1                  = $28  ; 40
MAP_PAL_TOWN_EXT_2                      = $29  ; 41
MAP_PAL_ZOZO_EXT_2                      = $2a  ; 42
MAP_PAL_KEFKAS_TOWER_2                  = $2b  ; 43
MAP_PAL_CLIFFS                          = $2c  ; 44
MAP_PAL_AIRSHIP_EXT_2                   = $2d  ; 45
MAP_PAL_DARILLS_TOMB_2                  = $2e  ; 46
MAP_PAL_MOUNTAINS_EXT_2                 = $2f  ; 47

MAP_PAL_ARRAY_LENGTH                    = $30  ; 48

.endif
.list on
