.list off
.ifndef MAP_GFX_BG3_INC
MAP_GFX_BG3_INC = 1

.global MapGfxBG3, MapGfxBG3Ptrs

MAP_GFX_BG3_MOUNTAINS_INT               = $00  ; 0
MAP_GFX_BG3_RIVER                       = $01  ; 1
MAP_GFX_BG3_UNUSED_TRAIN                = $02  ; 2
MAP_GFX_BG3_NARSHE_STEAM                = $03  ; 3
MAP_GFX_BG3_CAVES_TORCH                 = $04  ; 4
MAP_GFX_BG3_CAVES_ICE_WATER             = $05  ; 5
MAP_GFX_BG3_FOREST                      = $06  ; 6
MAP_GFX_BG3_BEACH                       = $07  ; 7
MAP_GFX_BG3_FIRE_WATER                  = $08  ; 8
MAP_GFX_BG3_BURNING_BUILDING            = $09  ; 9
MAP_GFX_BG3_RAIN                        = $0a  ; 10
MAP_GFX_BG3_CLOUDS                      = $0b  ; 11
MAP_GFX_BG3_DARILLS_TOMB                = $0c  ; 12
MAP_GFX_BG3_UNUSED_0D                   = $0d  ; 13
MAP_GFX_BG3_MAGITEK_TUBES               = $0e  ; 14
MAP_GFX_BG3_WATERFALL                   = $0f  ; 15
MAP_GFX_BG3_TOWN_WATER                  = $10  ; 16
MAP_GFX_BG3_MAGITEK_FACTORY             = $11  ; 17

MAP_GFX_BG3_ARRAY_LENGTH                = $12  ; 18

.endif
.list on
