.list off
.ifndef MAP_GFX_INC
MAP_GFX_INC = 1

.global MapGfx, MapGfxPtrs, MapAnimGfx

MAP_GFX_CASTLE_EXT_1                    = $00  ; 0
MAP_GFX_CASTLE_EXT_2                    = $01  ; 1
MAP_GFX_CASTLE_EXT_3                    = $02  ; 2
MAP_GFX_OPERA_1                         = $03  ; 3
MAP_GFX_TOWN_EXT_1                      = $04  ; 4
MAP_GFX_TOWN_EXT_2                      = $05  ; 5
MAP_GFX_TOWN_EXT_3                      = $06  ; 6
MAP_GFX_TOWN_EXT_4                      = $07  ; 7
MAP_GFX_TOWN_EXT_5                      = $08  ; 8
MAP_GFX_CASTLE_EXT_4                    = $09  ; 9
MAP_GFX_TOWN_EXT_6                      = $0a  ; 10
MAP_GFX_TOWN_EXT_7                      = $0b  ; 11
MAP_GFX_DOCKS_1                         = $0c  ; 12
MAP_GFX_DOCKS_2                         = $0d  ; 13
MAP_GFX_CAVES                           = $0e  ; 14
MAP_GFX_CASTLE_INT_1                    = $0f  ; 15
MAP_GFX_CASTLE_INT_2                    = $10  ; 16
MAP_GFX_CASTLE_INT_3                    = $11  ; 17
MAP_GFX_CASTLE_INT_4                    = $12  ; 18
MAP_GFX_DOCKS_3                         = $13  ; 19
MAP_GFX_RIVER                           = $14  ; 20
MAP_GFX_IMP_CAMP_1                      = $15  ; 21
MAP_GFX_IMP_CAMP_2                      = $16  ; 22
MAP_GFX_MOUNTAIN_INT_1                  = $17  ; 23
MAP_GFX_MOUNTAIN_INT_2                  = $18  ; 24
MAP_GFX_TOWN_INT_1                      = $19  ; 25
MAP_GFX_TOWN_INT_2                      = $1a  ; 26
MAP_GFX_TOWN_INT_3                      = $1b  ; 27
MAP_GFX_MOUNTAIN_EXT_1                  = $1c  ; 28
MAP_GFX_MOUNTAIN_EXT_2                  = $1d  ; 29
MAP_GFX_NARSHE_EXT_1                    = $1e  ; 30
MAP_GFX_NARSHE_EXT_2                    = $1f  ; 31
MAP_GFX_NARSHE_EXT_3                    = $20  ; 32
MAP_GFX_TOWN_EXT_8                      = $21  ; 33
MAP_GFX_NARSHE_EXT_4                    = $22  ; 34
MAP_GFX_KEFKAS_TOWER_1                  = $23  ; 35
MAP_GFX_KEFKAS_TOWER_2                  = $24  ; 36
MAP_GFX_BURNING_BUILDING                = $25  ; 37
MAP_GFX_TRAIN_EXT_1                     = $26  ; 38
MAP_GFX_TRAIN_EXT_2                     = $27  ; 39
MAP_GFX_TRAIN_EXT_3                     = $28  ; 40
MAP_GFX_FOREST_1                        = $29  ; 41
MAP_GFX_TRAIN_INT                       = $2a  ; 42
MAP_GFX_ZOZO_EXT_1                      = $2b  ; 43
MAP_GFX_ZOZO_EXT_2                      = $2c  ; 44
MAP_GFX_VECTOR_EXT                      = $2d  ; 45
MAP_GFX_DARILLS_TOMB_1                  = $2e  ; 46
MAP_GFX_MOUNTAINS_PARALLAX_1            = $2f  ; 47
MAP_GFX_FLOATING_ISLAND_1               = $30  ; 48
MAP_GFX_FLOATING_ISLAND_2               = $31  ; 49
MAP_GFX_MOUNTAINS_PARALLAX_2            = $32  ; 50
MAP_GFX_CASTLE_EXT_5                    = $33  ; 51
MAP_GFX_TOWN_EXT_9                      = $34  ; 52
MAP_GFX_WATERFALL_PARALLAX_1            = $35  ; 53
MAP_GFX_FACTORY_1                       = $36  ; 54
MAP_GFX_FACTORY_2                       = $37  ; 55
MAP_GFX_FACTORY_3                       = $38  ; 56
MAP_GFX_FACTORY_4                       = $39  ; 57
MAP_GFX_FACTORY_5                       = $3a  ; 58
MAP_GFX_AIRSHIP_1                       = $3b  ; 59
MAP_GFX_AIRSHIP_2                       = $3c  ; 60
MAP_GFX_AIRSHIP_3                       = $3d  ; 61
MAP_GFX_AIRSHIP_4                       = $3e  ; 62
MAP_GFX_CYANS_DREAM                     = $3f  ; 63
MAP_GFX_WATERFALL_PARALLAX_2            = $40  ; 64
MAP_GFX_FOREST_2                        = $41  ; 65
MAP_GFX_KEFKAS_TOWER_3                  = $42  ; 66
MAP_GFX_IMP_CASTLE_EXT_1                = $43  ; 67
MAP_GFX_IMP_CASTLE_EXT_2                = $44  ; 68
MAP_GFX_IMP_CASTLE_PARALLAX_1           = $45  ; 69
MAP_GFX_IMP_CASTLE_PARALLAX_2           = $46  ; 70
MAP_GFX_BEACH                           = $47  ; 71
MAP_GFX_IMP_CASTLE_INT                  = $48  ; 72
MAP_GFX_OPERA_2                         = $49  ; 73
MAP_GFX_TRAIN_PARALLAX                  = $4a  ; 74
MAP_GFX_SEALED_GATE_1                   = $4b  ; 75
MAP_GFX_SEALED_GATE_2                   = $4c  ; 76
MAP_GFX_SEALED_GATE_3                   = $4d  ; 77
MAP_GFX_FACTORY_6                       = $4e  ; 78
MAP_GFX_AIRSHIP_5                       = $4f  ; 79
MAP_GFX_BEACH_PARALLAX                  = $50  ; 80
MAP_GFX_DARILLS_TOMB_2                  = $51  ; 81

MAP_GFX_ARRAY_LENGTH                    = $52  ; 82

.endif
.list on
