.list off
.ifndef MAP_SPRITE_PAL_INC
MAP_SPRITE_PAL_INC = 1

.global MapSpritePal

MAP_SPRITE_PAL_EDGAR_SABIN_CELES        = $00  ; 0
MAP_SPRITE_PAL_LOCKE                    = $01  ; 1
MAP_SPRITE_PAL_TERRA                    = $02  ; 2
MAP_SPRITE_PAL_STRAGO_RELM_GAU_GOGO     = $03  ; 3
MAP_SPRITE_PAL_CYAN_SHADOW_SETZER       = $04  ; 4
MAP_SPRITE_PAL_MOG_UMARO                = $05  ; 5
MAP_SPRITE_PAL_RAINBOW                  = $06  ; 6
MAP_SPRITE_PAL_VEHICLE                  = $07  ; 7
MAP_SPRITE_PAL_ESPER_TERRA              = $08  ; 8
MAP_SPRITE_PAL_EDGAR_SABIN_CELES_ALT    = $09  ; 9
MAP_SPRITE_PAL_MACHINERY_1              = $0a  ; 10
MAP_SPRITE_PAL_RAFT                     = $0b  ; 11
MAP_SPRITE_PAL_MACHINERY_2              = $0c  ; 12
MAP_SPRITE_PAL_GUARDIAN                 = $0d  ; 13
MAP_SPRITE_PAL_SEALED_GATE              = $0e  ; 14
MAP_SPRITE_PAL_VECTOR_CRANE             = $0f  ; 15
MAP_SPRITE_PAL_STATUE_SMOKE             = $10  ; 16
MAP_SPRITE_PAL_TREASURE_CHEST           = $11  ; 17
MAP_SPRITE_PAL_CHADARNOOK               = $12  ; 18
MAP_SPRITE_PAL_ROCK                     = $13  ; 19
MAP_SPRITE_PAL_FALCON                   = $14  ; 20
MAP_SPRITE_PAL_ODIN                     = $15  ; 21
MAP_SPRITE_PAL_KEFKAS_TOWER_PARALLAX_1  = $16  ; 22
MAP_SPRITE_PAL_KEFKAS_TOWER_PARALLAX_2  = $17  ; 23
MAP_SPRITE_PAL_KEFKAS_TOWER_PARALLAX_3  = $18  ; 24
MAP_SPRITE_PAL_DADALUMA                 = $19  ; 25
MAP_SPRITE_PAL_GREEN_MAGICITE_SMOKE     = $1a  ; 26
MAP_SPRITE_PAL_UNUSED_27                = $1b  ; 27
MAP_SPRITE_PAL_UNUSED_28                = $1c  ; 28
MAP_SPRITE_PAL_AIRSHIP_PARALLAX         = $1d  ; 29
MAP_SPRITE_PAL_UNUSED_30                = $1e  ; 30
MAP_SPRITE_PAL_UNUSED_31                = $1f  ; 31

MAP_SPRITE_PAL_ARRAY_LENGTH             = $20  ; 32

.endif
.list on
