; ------------------------------------------------------------------------------

.global PortraitGfx, PortraitPal

; ------------------------------------------------------------------------------

.enum PORTRAIT
        TERRA                          ;= $00
        LOCKE                          ;= $01
        CYAN                           ;= $02
        SHADOW                         ;= $03
        EDGAR                          ;= $04
        SABIN                          ;= $05
        CELES                          ;= $06
        STRAGO                         ;= $07
        RELM                           ;= $08
        SETZER                         ;= $09
        MOG                            ;= $0a
        GAU                            ;= $0b
        GOGO                           ;= $0c
        UMARO                          ;= $0d
        SOLDIER                        ;= $0e
        IMP                            ;= $0f
        LEO                            ;= $10
        BANON                          ;= $11
        GHOST                          ;= $12
.endenum

; ------------------------------------------------------------------------------
