; ------------------------------------------------------------------------------

.global PortraitGfx, PortraitPal

; ------------------------------------------------------------------------------

PORTRAIT_TERRA                          = $00
PORTRAIT_LOCKE                          = $01
PORTRAIT_CYAN                           = $02
PORTRAIT_SHADOW                         = $03
PORTRAIT_EDGAR                          = $04
PORTRAIT_SABIN                          = $05
PORTRAIT_CELES                          = $06
PORTRAIT_STRAGO                         = $07
PORTRAIT_RELM                           = $08
PORTRAIT_SETZER                         = $09
PORTRAIT_MOG                            = $0a
PORTRAIT_GAU                            = $0b
PORTRAIT_GOGO                           = $0c
PORTRAIT_UMARO                          = $0d
PORTRAIT_SOLDIER                        = $0e
PORTRAIT_IMP                            = $0f
PORTRAIT_LEO                            = $10
PORTRAIT_BANON                          = $11
PORTRAIT_GHOST                          = $12

; ------------------------------------------------------------------------------
