.segment "monster_overlap"

; cf/3600
MonsterOverlap:
        .byte   0                       ; MONSTER_GUARD
        .byte   0                       ; MONSTER_SOLDIER
        .byte   0                       ; MONSTER_TEMPLAR
        .byte   0                       ; MONSTER_NINJA
        .byte   0                       ; MONSTER_SAMURAI
        .byte   0                       ; MONSTER_OROG
        .byte   0                       ; MONSTER_MAG_ROADER_1
        .byte   0                       ; MONSTER_RETAINER
        .byte   0                       ; MONSTER_HAZER
        .byte   0                       ; MONSTER_DAHLING
        .byte   0                       ; MONSTER_RAIN_MAN
        .byte   0                       ; MONSTER_BRAWLER
        .byte   0                       ; MONSTER_APOKRYPHOS
        .byte   0                       ; MONSTER_DARK_FORCE
        .byte   0                       ; MONSTER_WHISPER
        .byte   0                       ; MONSTER_OVER_MIND
        .byte   0                       ; MONSTER_OSTEOSAUR
        .byte   0                       ; MONSTER_COMMANDER
        .byte   0                       ; MONSTER_RHODOX
        .byte   0                       ; MONSTER_WERE_RAT
        .byte   0                       ; MONSTER_URSUS
        .byte   0                       ; MONSTER_RHINOTAUR
        .byte   0                       ; MONSTER_STEROIDITE
        .byte   0                       ; MONSTER_LEAFER
        .byte   0                       ; MONSTER_STRAY_CAT
        .byte   0                       ; MONSTER_LOBO
        .byte   0                       ; MONSTER_DOBERMAN
        .byte   0                       ; MONSTER_VOMAMMOTH
        .byte   0                       ; MONSTER_FIDOR
        .byte   0                       ; MONSTER_BASKERVOR
        .byte   0                       ; MONSTER_SURIANDER
        .byte   0                       ; MONSTER_CHIMERA
        .byte   0                       ; MONSTER_BEHEMOTH
        .byte   0                       ; MONSTER_MESOSAUR
        .byte   0                       ; MONSTER_PTERODON
        .byte   0                       ; MONSTER_FOSSILFANG
        .byte   0                       ; MONSTER_WHITE_DRGN
        .byte   0                       ; MONSTER_DOOM_DRGN
        .byte   0                       ; MONSTER_BRACHOSAUR
        .byte   0                       ; MONSTER_TYRANOSAUR
        .byte   0                       ; MONSTER_DARK_WIND
        .byte   0                       ; MONSTER_BEAKOR
        .byte   0                       ; MONSTER_VULTURE
        .byte   0                       ; MONSTER_HARPY
        .byte   0                       ; MONSTER_HERMITCRAB
        .byte   0                       ; MONSTER_TRAPPER
        .byte   0                       ; MONSTER_HORNET
        .byte   0                       ; MONSTER_CRASSHOPPR
        .byte   0                       ; MONSTER_DELTA_BUG
        .byte   0                       ; MONSTER_GILOMANTIS
        .byte   0                       ; MONSTER_TRILIUM
        .byte   0                       ; MONSTER_NIGHTSHADE
        .byte   0                       ; MONSTER_TUMBLEWEED
        .byte   0                       ; MONSTER_BLOOMPIRE
        .byte   0                       ; MONSTER_TRILOBITER
        .byte   0                       ; MONSTER_SIEGFRIED_1
        .byte   0                       ; MONSTER_NAUTILOID
        .byte   0                       ; MONSTER_EXOCITE
        .byte   0                       ; MONSTER_ANGUIFORM
        .byte   0                       ; MONSTER_REACH_FROG
        .byte   0                       ; MONSTER_LIZARD
        .byte   0                       ; MONSTER_CHICKENLIP
        .byte   0                       ; MONSTER_HOOVER
        .byte   0                       ; MONSTER_RIDER
        .byte   0                       ; MONSTER_CHUPON_COLOSSEUM
        .byte   0                       ; MONSTER_PIPSQUEAK
        .byte   0                       ; MONSTER_M_TEKARMOR
        .byte   0                       ; MONSTER_SKY_ARMOR
        .byte   0                       ; MONSTER_TELSTAR
        .byte   0                       ; MONSTER_LETHAL_WPN
        .byte   0                       ; MONSTER_VAPORITE
        .byte   0                       ; MONSTER_FLAN
        .byte   0                       ; MONSTER_ING
        .byte   0                       ; MONSTER_HUMPTY
        .byte   0                       ; MONSTER_BRAINPAN
        .byte   0                       ; MONSTER_CRULLER
        .byte   0                       ; MONSTER_CACTROT
        .byte   0                       ; MONSTER_REPO_MAN
        .byte   0                       ; MONSTER_HARVESTER
        .byte   0                       ; MONSTER_BOMB
        .byte   0                       ; MONSTER_STILL_LIFE
        .byte   0                       ; MONSTER_BOXED_SET
        .byte   0                       ; MONSTER_SLAMDANCER
        .byte   0                       ; MONSTER_HADESGIGAS
        .byte   0                       ; MONSTER_PUG
        .byte   0                       ; MONSTER_MAGIC_URN
        .byte   0                       ; MONSTER_MOVER
        .byte   0                       ; MONSTER_FIGALIZ
        .byte   0                       ; MONSTER_BUFFALAX
        .byte   0                       ; MONSTER_ASPIK
        .byte   0                       ; MONSTER_GHOST
        .byte   0                       ; MONSTER_CRAWLER
        .byte   0                       ; MONSTER_SAND_RAY
        .byte   0                       ; MONSTER_ARENEID
        .byte   0                       ; MONSTER_ACTANEON
        .byte   0                       ; MONSTER_SAND_HORSE
        .byte   0                       ; MONSTER_DARK_SIDE
        .byte   0                       ; MONSTER_MAD_OSCAR
        .byte   0                       ; MONSTER_CRAWLY
        .byte   0                       ; MONSTER_BLEARY
        .byte   0                       ; MONSTER_MARSHAL
        .byte   0                       ; MONSTER_TROOPER
        .byte   0                       ; MONSTER_GENERAL
        .byte   0                       ; MONSTER_COVERT
        .byte   0                       ; MONSTER_OGOR
        .byte   0                       ; MONSTER_WARLOCK
        .byte   0                       ; MONSTER_MADAM
        .byte   0                       ; MONSTER_JOKER
        .byte   0                       ; MONSTER_IRON_FIST
        .byte   0                       ; MONSTER_GOBLIN
        .byte   0                       ; MONSTER_APPARITE
        .byte   0                       ; MONSTER_POWERDEMON
        .byte   0                       ; MONSTER_DISPLAYER
        .byte   0                       ; MONSTER_VECTOR_PUP
        .byte   0                       ; MONSTER_PEEPERS
        .byte   0                       ; MONSTER_SEWER_RAT
        .byte   0                       ; MONSTER_SLATTER
        .byte   0                       ; MONSTER_RHINOX
        .byte   0                       ; MONSTER_RHOBITE
        .byte   0                       ; MONSTER_WILD_CAT
        .byte   0                       ; MONSTER_RED_FANG
        .byte   0                       ; MONSTER_BOUNTY_MAN
        .byte   0                       ; MONSTER_TUSKER
        .byte   0                       ; MONSTER_RALPH
        .byte   0                       ; MONSTER_CHITONID
        .byte   0                       ; MONSTER_WART_PUCK
        .byte   0                       ; MONSTER_RHYOS
        .byte   0                       ; MONSTER_SRBEHEMOTH_UNDEAD
        .byte   0                       ; MONSTER_VECTAUR
        .byte   0                       ; MONSTER_WYVERN
        .byte   0                       ; MONSTER_ZOMBONE
        .byte   0                       ; MONSTER_DRAGON
        .byte   0                       ; MONSTER_BRONTAUR
        .byte   0                       ; MONSTER_ALLOSAURUS
        .byte   0                       ; MONSTER_CIRPIUS
        .byte   0                       ; MONSTER_SPRINTER
        .byte   0                       ; MONSTER_GOBBLER
        .byte   0                       ; MONSTER_HARPIAI
        .byte   0                       ; MONSTER_GLOOMSHELL
        .byte   0                       ; MONSTER_DROP
        .byte   0                       ; MONSTER_MIND_CANDY
        .byte   0                       ; MONSTER_WEEDFEEDER
        .byte   0                       ; MONSTER_LURIDAN
        .byte   0                       ; MONSTER_TOE_CUTTER
        .byte   0                       ; MONSTER_OVER_GRUNK
        .byte   0                       ; MONSTER_EXORAY
        .byte   0                       ; MONSTER_CRUSHER
        .byte   0                       ; MONSTER_UROBUROS
        .byte   0                       ; MONSTER_PRIMORDITE
        .byte   0                       ; MONSTER_SKY_CAP
        .byte   0                       ; MONSTER_CEPHALER
        .byte   0                       ; MONSTER_MALIGA
        .byte   0                       ; MONSTER_GIGAN_TOAD
        .byte   0                       ; MONSTER_GECKOREX
        .byte   0                       ; MONSTER_CLUCK
        .byte   0                       ; MONSTER_LAND_WORM
        .byte   0                       ; MONSTER_TEST_RIDER
        .byte   0                       ; MONSTER_PLUTOARMOR
        .byte   0                       ; MONSTER_TOMB_THUMB
        .byte   0                       ; MONSTER_HEAVYARMOR
        .byte   0                       ; MONSTER_CHASER
        .byte   0                       ; MONSTER_SCULLION
        .byte   0                       ; MONSTER_POPLIUM
        .byte   0                       ; MONSTER_INTANGIR
        .byte   0                       ; MONSTER_MISFIT
        .byte   0                       ; MONSTER_ELAND
        .byte   0                       ; MONSTER_ENUO
        .byte   0                       ; MONSTER_DEEP_EYE
        .byte   0                       ; MONSTER_GREASEMONK
        .byte   0                       ; MONSTER_NECKHUNTER
        .byte   0                       ; MONSTER_GRENADE
        .byte   0                       ; MONSTER_CRITIC
        .byte   0                       ; MONSTER_PAN_DORA
        .byte   0                       ; MONSTER_SOULDANCER
        .byte   0                       ; MONSTER_GIGANTOS
        .byte   0                       ; MONSTER_MAG_ROADER_2
        .byte   0                       ; MONSTER_SPEK_TOR
        .byte   0                       ; MONSTER_PARASITE
        .byte   0                       ; MONSTER_EARTHGUARD
        .byte   0                       ; MONSTER_COELECITE
        .byte   0                       ; MONSTER_ANEMONE
        .byte   0                       ; MONSTER_HIPOCAMPUS
        .byte   0                       ; MONSTER_SPECTRE
        .byte   0                       ; MONSTER_EVIL_OSCAR
        .byte   0                       ; MONSTER_SLURM
        .byte   0                       ; MONSTER_LATIMERIA
        .byte   0                       ; MONSTER_STILLGOING
        .byte   0                       ; MONSTER_ALLO_VER
        .byte   0                       ; MONSTER_PHASE
        .byte   0                       ; MONSTER_OUTSIDER
        .byte   0                       ; MONSTER_BARB_E
        .byte   0                       ; MONSTER_PARASOUL
        .byte   0                       ; MONSTER_PM_STALKER
        .byte   0                       ; MONSTER_HEMOPHYTE
        .byte   0                       ; MONSTER_SP_FORCES
        .byte   0                       ; MONSTER_NOHRABBIT
        .byte   0                       ; MONSTER_WIZARD
        .byte   0                       ; MONSTER_SCRAPPER
        .byte   0                       ; MONSTER_CERITOPS
        .byte   0                       ; MONSTER_COMMANDO
        .byte   0                       ; MONSTER_OPINICUS
        .byte   0                       ; MONSTER_POPPERS
        .byte   0                       ; MONSTER_LUNARIS
        .byte   0                       ; MONSTER_GARM
        .byte   0                       ; MONSTER_VINDR
        .byte   0                       ; MONSTER_KIWOK
        .byte   0                       ; MONSTER_NASTIDON
        .byte   0                       ; MONSTER_RINN
        .byte   0                       ; MONSTER_INSECARE
        .byte   0                       ; MONSTER_VERMIN
        .byte   0                       ; MONSTER_MANTODEA
        .byte   0                       ; MONSTER_BOGY
        .byte   0                       ; MONSTER_PRUSSIAN
        .byte   0                       ; MONSTER_BLACK_DRGN
        .byte   0                       ; MONSTER_ADAMANCHYT
        .byte   0                       ; MONSTER_DANTE
        .byte   0                       ; MONSTER_WIREY_DRGN
        .byte   0                       ; MONSTER_DUELLER
        .byte   0                       ; MONSTER_PSYCHOT
        .byte   0                       ; MONSTER_MUUS
        .byte   0                       ; MONSTER_KARKASS
        .byte   0                       ; MONSTER_PUNISHER
        .byte   0                       ; MONSTER_BALLOON
        .byte   0                       ; MONSTER_GABBLDEGAK
        .byte   0                       ; MONSTER_GTBEHEMOTH
        .byte   0                       ; MONSTER_SCORPION
        .byte   0                       ; MONSTER_CHAOS_DRGN
        .byte   0                       ; MONSTER_SPIT_FIRE
        .byte   0                       ; MONSTER_VECTAGOYLE
        .byte   0                       ; MONSTER_LICH
        .byte   0                       ; MONSTER_OSPREY
        .byte   0                       ; MONSTER_MAG_ROADER_3
        .byte   0                       ; MONSTER_BUG
        .byte   0                       ; MONSTER_SEA_FLOWER
        .byte   0                       ; MONSTER_FORTIS
        .byte   0                       ; MONSTER_ABOLISHER
        .byte   0                       ; MONSTER_AQUILA
        .byte   0                       ; MONSTER_JUNK
        .byte   0                       ; MONSTER_MANDRAKE
        .byte   0                       ; MONSTER_1ST_CLASS
        .byte   0                       ; MONSTER_TAP_DANCER
        .byte   0                       ; MONSTER_NECROMANCR
        .byte   0                       ; MONSTER_BORRAS
        .byte   0                       ; MONSTER_MAG_ROADER_4
        .byte   0                       ; MONSTER_WILD_RAT
        .byte   72                      ; MONSTER_GOLD_BEAR
        .byte   0                       ; MONSTER_INNOC
        .byte   0                       ; MONSTER_TRIXTER
        .byte   0                       ; MONSTER_RED_WOLF
        .byte   0                       ; MONSTER_DIDALOS
        .byte   0                       ; MONSTER_WOOLLY
        .byte   0                       ; MONSTER_VETERAN
        .byte   0                       ; MONSTER_SKY_BASE
        .byte   0                       ; MONSTER_IRONHITMAN
        .byte   72                      ; MONSTER_IO
        .byte   0                       ; MONSTER_PUGS
        .byte   0                       ; MONSTER_WHELK
        .byte   0                       ; MONSTER_PRESENTER
        .byte   0                       ; MONSTER_MEGA_ARMOR
        .byte   0                       ; MONSTER_VARGAS
        .byte   0                       ; MONSTER_TUNNELARMR
        .byte   0                       ; MONSTER_PROMETHEUS
        .byte   0                       ; MONSTER_GHOSTTRAIN
        .byte   0                       ; MONSTER_DADALUMA
        .byte   0                       ; MONSTER_SHIVA
        .byte   0                       ; MONSTER_IFRIT
        .byte   0                       ; MONSTER_NUMBER_024
        .byte   0                       ; MONSTER_NUMBER_128
        .byte   0                       ; MONSTER_INFERNO
        .byte   0                       ; MONSTER_CRANE_1
        .byte   0                       ; MONSTER_CRANE_2
        .byte   0                       ; MONSTER_UMARO_1
        .byte   0                       ; MONSTER_UMARO_2
        .byte   0                       ; MONSTER_GUARDIAN_VECTOR
        .byte   0                       ; MONSTER_GUARDIAN_BOSS
        .byte   0                       ; MONSTER_AIR_FORCE
        .byte   0                       ; MONSTER_TRITOCH_INTRO
        .byte   0                       ; MONSTER_TRITOCH_MORPH
        .byte   0                       ; MONSTER_FLAMEEATER
        .byte   0                       ; MONSTER_ATMAWEAPON
        .byte   0                       ; MONSTER_NERAPA
        .byte   0                       ; MONSTER_SRBEHEMOTH
        .byte   0                       ; MONSTER_KEFKA_1
        .byte   72                      ; MONSTER_TENTACLE
        .byte   0                       ; MONSTER_DULLAHAN
        .byte   0                       ; MONSTER_DOOM_GAZE
        .byte   0                       ; MONSTER_CHADARNOOK_1
        .byte   0                       ; MONSTER_CURLEY
        .byte   0                       ; MONSTER_LARRY
        .byte   0                       ; MONSTER_MOE
        .byte   0                       ; MONSTER_WREXSOUL
        .byte   0                       ; MONSTER_HIDON
        .byte   0                       ; MONSTER_KATANASOUL
        .byte   0                       ; MONSTER_L30_MAGIC
        .byte   0                       ; MONSTER_HIDONITE
        .byte   0                       ; MONSTER_DOOM
        .byte   0                       ; MONSTER_GODDESS
        .byte   0                       ; MONSTER_POLTRGEIST
        .byte   0                       ; MONSTER_FINAL_KEFKA
        .byte   0                       ; MONSTER_L40_MAGIC
        .byte   0                       ; MONSTER_ULTROS_RIVER
        .byte   0                       ; MONSTER_ULTROS_OPERA
        .byte   0                       ; MONSTER_ULTROS_MOUNTAIN
        .byte   0                       ; MONSTER_CHUPON_AIRSHIP
        .byte   0                       ; MONSTER_L20_MAGIC
        .byte   0                       ; MONSTER_SIEGFRIED_2
        .byte   0                       ; MONSTER_L10_MAGIC
        .byte   0                       ; MONSTER_L50_MAGIC
        .byte   8                       ; MONSTER_HEAD
        .byte   8                       ; MONSTER_WHELK_HEAD
        .byte   0                       ; MONSTER_COLOSSUS
        .byte   0                       ; MONSTER_CZARDRAGON
        .byte   0                       ; MONSTER_MASTER_PUG
        .byte   0                       ; MONSTER_L60_MAGIC
        .byte   0                       ; MONSTER_MERCHANT
        .byte   0                       ; MONSTER_B_DAY_SUIT
        .byte   72                      ; MONSTER_TENTACLE_1
        .byte   32                      ; MONSTER_TENTACLE_2
        .byte   32                      ; MONSTER_TENTACLE_3
        .byte   48                      ; MONSTER_RIGHTBLADE
        .byte   64                      ; MONSTER_LEFT_BLADE
        .byte   48                      ; MONSTER_ROUGH
        .byte   16                      ; MONSTER_STRIKER
        .byte   0                       ; MONSTER_L70_MAGIC
        .byte   0                       ; MONSTER_TRITOCH_BOSS
        .byte   0                       ; MONSTER_LASER_GUN
        .byte   0                       ; MONSTER_SPECK
        .byte   24                      ; MONSTER_MISSILEBAY
        .byte   0                       ; MONSTER_CHADARNOOK_2
        .byte   0                       ; MONSTER_ICE_DRAGON
        .byte   0                       ; MONSTER_KEFKA_NARSHE
        .byte   0                       ; MONSTER_STORM_DRGN
        .byte   0                       ; MONSTER_DIRT_DRGN
        .byte   0                       ; MONSTER_IPOOH
        .byte   0                       ; MONSTER_LEADER
        .byte   0                       ; MONSTER_GRUNT
        .byte   0                       ; MONSTER_GOLD_DRGN
        .byte   0                       ; MONSTER_SKULL_DRGN
        .byte   0                       ; MONSTER_BLUE_DRGN
        .byte   0                       ; MONSTER_RED_DRAGON
        .byte   0                       ; MONSTER_PIRANHA
        .byte   0                       ; MONSTER_RIZOPAS
        .byte   0                       ; MONSTER_SPECTER
        .byte   0                       ; MONSTER_SHORT_ARM
        .byte   0                       ; MONSTER_LONG_ARM
        .byte   0                       ; MONSTER_FACE
        .byte   0                       ; MONSTER_TIGER
        .byte   0                       ; MONSTER_TOOLS
        .byte   0                       ; MONSTER_MAGIC
        .byte   0                       ; MONSTER_HIT
        .byte   0                       ; MONSTER_GIRL
        .byte   0                       ; MONSTER_SLEEP
        .byte   1                       ; MONSTER_HIDONITE_1
        .byte   0                       ; MONSTER_HIDONITE_2
        .byte   0                       ; MONSTER_HIDONITE_3
        .byte   0                       ; MONSTER_L80_MAGIC
        .byte   0                       ; MONSTER_L90_MAGIC
        .byte   0                       ; MONSTER_PROTOARMOR
        .byte   0                       ; MONSTER_MAGIMASTER
        .byte   0                       ; MONSTER_SOULSAVER
        .byte   0                       ; MONSTER_ULTROS_AIRSHIP
        .byte   0                       ; MONSTER_NAUGHTY
        .byte   0                       ; MONSTER_PHUNBABA_1
        .byte   0                       ; MONSTER_PHUNBABA_2
        .byte   0                       ; MONSTER_PHUNBABA_3
        .byte   0                       ; MONSTER_PHUNBABA_4
        .byte   0                       ; MONSTER_TERRA_FLASHBACK
        .byte   0                       ; MONSTER_KEFKA_IMP_CAMP
        .byte   0                       ; MONSTER_CYAN_IMP_CAMP
        .byte   0                       ; MONSTER_ZONE_EATER
        .byte   0                       ; MONSTER_GAU_VELDT
        .byte   0                       ; MONSTER_KEFKA_VS_LEO
        .byte   0                       ; MONSTER_KEFKA_ESPER_GATE
        .byte   0                       ; MONSTER_OFFICER
        .byte   0                       ; MONSTER_CADET
        .byte   0                       ; MONSTER_0177
        .byte   0                       ; MONSTER_0178
        .byte   0                       ; MONSTER_SOLDIER_FLASHBACK
        .byte   0                       ; MONSTER_KEFKA_VS_ESPER
        .byte   0                       ; MONSTER_EVENT
        .byte   0                       ; MONSTER_017C
        .byte   0                       ; MONSTER_ATMA
        .byte   0                       ; MONSTER_SHADOW_COLOSSEUM
        .byte   0                       ; MONSTER_COLOSSEUM
