; ------------------------------------------------------------------------------

.segment "monster_overlap"

; cf/3600
MonsterOverlap:
        .byte   0                       ; GUARD
        .byte   0                       ; SOLDIER
        .byte   0                       ; TEMPLAR
        .byte   0                       ; NINJA
        .byte   0                       ; SAMURAI
        .byte   0                       ; OROG
        .byte   0                       ; MAG_ROADER_1
        .byte   0                       ; RETAINER
        .byte   0                       ; HAZER
        .byte   0                       ; DAHLING
        .byte   0                       ; RAIN_MAN
        .byte   0                       ; BRAWLER
        .byte   0                       ; APOKRYPHOS
        .byte   0                       ; DARK_FORCE
        .byte   0                       ; WHISPER
        .byte   0                       ; OVER_MIND
        .byte   0                       ; OSTEOSAUR
        .byte   0                       ; COMMANDER
        .byte   0                       ; RHODOX
        .byte   0                       ; WERE_RAT
        .byte   0                       ; URSUS
        .byte   0                       ; RHINOTAUR
        .byte   0                       ; STEROIDITE
        .byte   0                       ; LEAFER
        .byte   0                       ; STRAY_CAT
        .byte   0                       ; LOBO
        .byte   0                       ; DOBERMAN
        .byte   0                       ; VOMAMMOTH
        .byte   0                       ; FIDOR
        .byte   0                       ; BASKERVOR
        .byte   0                       ; SURIANDER
        .byte   0                       ; CHIMERA
        .byte   0                       ; BEHEMOTH
        .byte   0                       ; MESOSAUR
        .byte   0                       ; PTERODON
        .byte   0                       ; FOSSILFANG
        .byte   0                       ; WHITE_DRGN
        .byte   0                       ; DOOM_DRGN
        .byte   0                       ; BRACHOSAUR
        .byte   0                       ; TYRANOSAUR
        .byte   0                       ; DARK_WIND
        .byte   0                       ; BEAKOR
        .byte   0                       ; VULTURE
        .byte   0                       ; HARPY
        .byte   0                       ; HERMITCRAB
        .byte   0                       ; TRAPPER
        .byte   0                       ; HORNET
        .byte   0                       ; CRASSHOPPR
        .byte   0                       ; DELTA_BUG
        .byte   0                       ; GILOMANTIS
        .byte   0                       ; TRILIUM
        .byte   0                       ; NIGHTSHADE
        .byte   0                       ; TUMBLEWEED
        .byte   0                       ; BLOOMPIRE
        .byte   0                       ; TRILOBITER
        .byte   0                       ; SIEGFRIED_1
        .byte   0                       ; NAUTILOID
        .byte   0                       ; EXOCITE
        .byte   0                       ; ANGUIFORM
        .byte   0                       ; REACH_FROG
        .byte   0                       ; LIZARD
        .byte   0                       ; CHICKENLIP
        .byte   0                       ; HOOVER
        .byte   0                       ; RIDER
        .byte   0                       ; CHUPON_COLOSSEUM
        .byte   0                       ; PIPSQUEAK
        .byte   0                       ; M_TEKARMOR
        .byte   0                       ; SKY_ARMOR
        .byte   0                       ; TELSTAR
        .byte   0                       ; LETHAL_WPN
        .byte   0                       ; VAPORITE
        .byte   0                       ; FLAN
        .byte   0                       ; ING
        .byte   0                       ; HUMPTY
        .byte   0                       ; BRAINPAN
        .byte   0                       ; CRULLER
        .byte   0                       ; CACTROT
        .byte   0                       ; REPO_MAN
        .byte   0                       ; HARVESTER
        .byte   0                       ; BOMB
        .byte   0                       ; STILL_LIFE
        .byte   0                       ; BOXED_SET
        .byte   0                       ; SLAMDANCER
        .byte   0                       ; HADESGIGAS
        .byte   0                       ; PUG
        .byte   0                       ; MAGIC_URN
        .byte   0                       ; MOVER
        .byte   0                       ; FIGALIZ
        .byte   0                       ; BUFFALAX
        .byte   0                       ; ASPIK
        .byte   0                       ; GHOST
        .byte   0                       ; CRAWLER
        .byte   0                       ; SAND_RAY
        .byte   0                       ; ARENEID
        .byte   0                       ; ACTANEON
        .byte   0                       ; SAND_HORSE
        .byte   0                       ; DARK_SIDE
        .byte   0                       ; MAD_OSCAR
        .byte   0                       ; CRAWLY
        .byte   0                       ; BLEARY
        .byte   0                       ; MARSHAL
        .byte   0                       ; TROOPER
        .byte   0                       ; GENERAL
        .byte   0                       ; COVERT
        .byte   0                       ; OGOR
        .byte   0                       ; WARLOCK
        .byte   0                       ; MADAM
        .byte   0                       ; JOKER
        .byte   0                       ; IRON_FIST
        .byte   0                       ; GOBLIN
        .byte   0                       ; APPARITE
        .byte   0                       ; POWERDEMON
        .byte   0                       ; DISPLAYER
        .byte   0                       ; VECTOR_PUP
        .byte   0                       ; PEEPERS
        .byte   0                       ; SEWER_RAT
        .byte   0                       ; SLATTER
        .byte   0                       ; RHINOX
        .byte   0                       ; RHOBITE
        .byte   0                       ; WILD_CAT
        .byte   0                       ; RED_FANG
        .byte   0                       ; BOUNTY_MAN
        .byte   0                       ; TUSKER
        .byte   0                       ; RALPH
        .byte   0                       ; CHITONID
        .byte   0                       ; WART_PUCK
        .byte   0                       ; RHYOS
        .byte   0                       ; SRBEHEMOTH_UNDEAD
        .byte   0                       ; VECTAUR
        .byte   0                       ; WYVERN
        .byte   0                       ; ZOMBONE
        .byte   0                       ; DRAGON
        .byte   0                       ; BRONTAUR
        .byte   0                       ; ALLOSAURUS
        .byte   0                       ; CIRPIUS
        .byte   0                       ; SPRINTER
        .byte   0                       ; GOBBLER
        .byte   0                       ; HARPIAI
        .byte   0                       ; GLOOMSHELL
        .byte   0                       ; DROP
        .byte   0                       ; MIND_CANDY
        .byte   0                       ; WEEDFEEDER
        .byte   0                       ; LURIDAN
        .byte   0                       ; TOE_CUTTER
        .byte   0                       ; OVER_GRUNK
        .byte   0                       ; EXORAY
        .byte   0                       ; CRUSHER
        .byte   0                       ; UROBUROS
        .byte   0                       ; PRIMORDITE
        .byte   0                       ; SKY_CAP
        .byte   0                       ; CEPHALER
        .byte   0                       ; MALIGA
        .byte   0                       ; GIGAN_TOAD
        .byte   0                       ; GECKOREX
        .byte   0                       ; CLUCK
        .byte   0                       ; LAND_WORM
        .byte   0                       ; TEST_RIDER
        .byte   0                       ; PLUTOARMOR
        .byte   0                       ; TOMB_THUMB
        .byte   0                       ; HEAVYARMOR
        .byte   0                       ; CHASER
        .byte   0                       ; SCULLION
        .byte   0                       ; POPLIUM
        .byte   0                       ; INTANGIR
        .byte   0                       ; MISFIT
        .byte   0                       ; ELAND
        .byte   0                       ; ENUO
        .byte   0                       ; DEEP_EYE
        .byte   0                       ; GREASEMONK
        .byte   0                       ; NECKHUNTER
        .byte   0                       ; GRENADE
        .byte   0                       ; CRITIC
        .byte   0                       ; PAN_DORA
        .byte   0                       ; SOULDANCER
        .byte   0                       ; GIGANTOS
        .byte   0                       ; MAG_ROADER_2
        .byte   0                       ; SPEK_TOR
        .byte   0                       ; PARASITE
        .byte   0                       ; EARTHGUARD
        .byte   0                       ; COELECITE
        .byte   0                       ; ANEMONE
        .byte   0                       ; HIPOCAMPUS
        .byte   0                       ; SPECTRE
        .byte   0                       ; EVIL_OSCAR
        .byte   0                       ; SLURM
        .byte   0                       ; LATIMERIA
        .byte   0                       ; STILLGOING
        .byte   0                       ; ALLO_VER
        .byte   0                       ; PHASE
        .byte   0                       ; OUTSIDER
        .byte   0                       ; BARB_E
        .byte   0                       ; PARASOUL
        .byte   0                       ; PM_STALKER
        .byte   0                       ; HEMOPHYTE
        .byte   0                       ; SP_FORCES
        .byte   0                       ; NOHRABBIT
        .byte   0                       ; WIZARD
        .byte   0                       ; SCRAPPER
        .byte   0                       ; CERITOPS
        .byte   0                       ; COMMANDO
        .byte   0                       ; OPINICUS
        .byte   0                       ; POPPERS
        .byte   0                       ; LUNARIS
        .byte   0                       ; GARM
        .byte   0                       ; VINDR
        .byte   0                       ; KIWOK
        .byte   0                       ; NASTIDON
        .byte   0                       ; RINN
        .byte   0                       ; INSECARE
        .byte   0                       ; VERMIN
        .byte   0                       ; MANTODEA
        .byte   0                       ; BOGY
        .byte   0                       ; PRUSSIAN
        .byte   0                       ; BLACK_DRGN
        .byte   0                       ; ADAMANCHYT
        .byte   0                       ; DANTE
        .byte   0                       ; WIREY_DRGN
        .byte   0                       ; DUELLER
        .byte   0                       ; PSYCHOT
        .byte   0                       ; MUUS
        .byte   0                       ; KARKASS
        .byte   0                       ; PUNISHER
        .byte   0                       ; BALLOON
        .byte   0                       ; GABBLDEGAK
        .byte   0                       ; GTBEHEMOTH
        .byte   0                       ; SCORPION
        .byte   0                       ; CHAOS_DRGN
        .byte   0                       ; SPIT_FIRE
        .byte   0                       ; VECTAGOYLE
        .byte   0                       ; LICH
        .byte   0                       ; OSPREY
        .byte   0                       ; MAG_ROADER_3
        .byte   0                       ; BUG
        .byte   0                       ; SEA_FLOWER
        .byte   0                       ; FORTIS
        .byte   0                       ; ABOLISHER
        .byte   0                       ; AQUILA
        .byte   0                       ; JUNK
        .byte   0                       ; MANDRAKE
        .byte   0                       ; 1ST_CLASS
        .byte   0                       ; TAP_DANCER
        .byte   0                       ; NECROMANCR
        .byte   0                       ; BORRAS
        .byte   0                       ; MAG_ROADER_4
        .byte   0                       ; WILD_RAT
        .byte   72                      ; GOLD_BEAR
        .byte   0                       ; INNOC
        .byte   0                       ; TRIXTER
        .byte   0                       ; RED_WOLF
        .byte   0                       ; DIDALOS
        .byte   0                       ; WOOLLY
        .byte   0                       ; VETERAN
        .byte   0                       ; SKY_BASE
        .byte   0                       ; IRONHITMAN
        .byte   72                      ; IO
        .byte   0                       ; PUGS
        .byte   0                       ; WHELK
        .byte   0                       ; PRESENTER
        .byte   0                       ; MEGA_ARMOR
        .byte   0                       ; VARGAS
        .byte   0                       ; TUNNELARMR
        .byte   0                       ; PROMETHEUS
        .byte   0                       ; GHOSTTRAIN
        .byte   0                       ; DADALUMA
        .byte   0                       ; SHIVA
        .byte   0                       ; IFRIT
        .byte   0                       ; NUMBER_024
        .byte   0                       ; NUMBER_128
        .byte   0                       ; INFERNO
        .byte   0                       ; CRANE_1
        .byte   0                       ; CRANE_2
        .byte   0                       ; UMARO_1
        .byte   0                       ; UMARO_2
        .byte   0                       ; GUARDIAN_VECTOR
        .byte   0                       ; GUARDIAN_BOSS
        .byte   0                       ; AIR_FORCE
        .byte   0                       ; TRITOCH_INTRO
        .byte   0                       ; TRITOCH_MORPH
        .byte   0                       ; FLAMEEATER
        .byte   0                       ; ATMAWEAPON
        .byte   0                       ; NERAPA
        .byte   0                       ; SRBEHEMOTH
        .byte   0                       ; KEFKA_1
        .byte   72                      ; TENTACLE
        .byte   0                       ; DULLAHAN
        .byte   0                       ; DOOM_GAZE
        .byte   0                       ; CHADARNOOK_1
        .byte   0                       ; CURLEY
        .byte   0                       ; LARRY
        .byte   0                       ; MOE
        .byte   0                       ; WREXSOUL
        .byte   0                       ; HIDON
        .byte   0                       ; KATANASOUL
        .byte   0                       ; L30_MAGIC
        .byte   0                       ; HIDONITE
        .byte   0                       ; DOOM
        .byte   0                       ; GODDESS
        .byte   0                       ; POLTRGEIST
        .byte   0                       ; FINAL_KEFKA
        .byte   0                       ; L40_MAGIC
        .byte   0                       ; ULTROS_RIVER
        .byte   0                       ; ULTROS_OPERA
        .byte   0                       ; ULTROS_MOUNTAIN
        .byte   0                       ; CHUPON_AIRSHIP
        .byte   0                       ; L20_MAGIC
        .byte   0                       ; SIEGFRIED_2
        .byte   0                       ; L10_MAGIC
        .byte   0                       ; L50_MAGIC
        .byte   8                       ; HEAD
        .byte   8                       ; WHELK_HEAD
        .byte   0                       ; COLOSSUS
        .byte   0                       ; CZARDRAGON
        .byte   0                       ; MASTER_PUG
        .byte   0                       ; L60_MAGIC
        .byte   0                       ; MERCHANT
        .byte   0                       ; B_DAY_SUIT
        .byte   72                      ; TENTACLE_1
        .byte   32                      ; TENTACLE_2
        .byte   32                      ; TENTACLE_3
        .byte   48                      ; RIGHTBLADE
        .byte   64                      ; LEFT_BLADE
        .byte   48                      ; ROUGH
        .byte   16                      ; STRIKER
        .byte   0                       ; L70_MAGIC
        .byte   0                       ; TRITOCH_BOSS
        .byte   0                       ; LASER_GUN
        .byte   0                       ; SPECK
        .byte   24                      ; MISSILEBAY
        .byte   0                       ; CHADARNOOK_2
        .byte   0                       ; ICE_DRAGON
        .byte   0                       ; KEFKA_NARSHE
        .byte   0                       ; STORM_DRGN
        .byte   0                       ; DIRT_DRGN
        .byte   0                       ; IPOOH
        .byte   0                       ; LEADER
        .byte   0                       ; GRUNT
        .byte   0                       ; GOLD_DRGN
        .byte   0                       ; SKULL_DRGN
        .byte   0                       ; BLUE_DRGN
        .byte   0                       ; RED_DRAGON
        .byte   0                       ; PIRANHA
        .byte   0                       ; RIZOPAS
        .byte   0                       ; SPECTER
        .byte   0                       ; SHORT_ARM
        .byte   0                       ; LONG_ARM
        .byte   0                       ; FACE
        .byte   0                       ; TIGER
        .byte   0                       ; TOOLS
        .byte   0                       ; MAGIC
        .byte   0                       ; HIT
        .byte   0                       ; GIRL
        .byte   0                       ; SLEEP
        .byte   1                       ; HIDONITE_1
        .byte   0                       ; HIDONITE_2
        .byte   0                       ; HIDONITE_3
        .byte   0                       ; L80_MAGIC
        .byte   0                       ; L90_MAGIC
        .byte   0                       ; PROTOARMOR
        .byte   0                       ; MAGIMASTER
        .byte   0                       ; SOULSAVER
        .byte   0                       ; ULTROS_AIRSHIP
        .byte   0                       ; NAUGHTY
        .byte   0                       ; PHUNBABA_1
        .byte   0                       ; PHUNBABA_2
        .byte   0                       ; PHUNBABA_3
        .byte   0                       ; PHUNBABA_4
        .byte   0                       ; TERRA_FLASHBACK
        .byte   0                       ; KEFKA_IMP_CAMP
        .byte   0                       ; CYAN_IMP_CAMP
        .byte   0                       ; ZONE_EATER
        .byte   0                       ; GAU_VELDT
        .byte   0                       ; KEFKA_VS_LEO
        .byte   0                       ; KEFKA_ESPER_GATE
        .byte   0                       ; OFFICER
        .byte   0                       ; CADET
        .byte   0                       ; MONSTER_0177
        .byte   0                       ; MONSTER_0178
        .byte   0                       ; SOLDIER_FLASHBACK
        .byte   0                       ; KEFKA_VS_ESPER
        .byte   0                       ; EVENT
        .byte   0                       ; MONSTER_017C
        .byte   0                       ; ATMA
        .byte   0                       ; SHADOW_COLOSSEUM
        .byte   0                       ; COLOSSEUM

; ------------------------------------------------------------------------------
