.list off
.ifndef SAMPLE_BRR_INC
SAMPLE_BRR_INC = 1

.global SampleBRR, SampleBRRPtrs

; instrument sample ids
SAMPLE_GUITAR_STEEL                     = $00  ; 0
SAMPLE_BASS_FINGER                      = $01  ; 1
SAMPLE_PAN_FLUTE                        = $02  ; 2
SAMPLE_BANJO                            = $03  ; 3
SAMPLE_CELLO                            = $04  ; 4
SAMPLE_VOICE_SYNTH                      = $05  ; 5
SAMPLE_FLUTE                            = $06  ; 6
SAMPLE_FRENCH_HORN                      = $07  ; 7
SAMPLE_SYNTH                            = $08  ; 8
SAMPLE_OBOE                             = $09  ; 9
SAMPLE_ROCK_ORGAN                       = $0a  ; 10
SAMPLE_PIANO                            = $0b  ; 11
SAMPLE_STRINGS                          = $0c  ; 12
SAMPLE_TRUMPET                          = $0d  ; 13
SAMPLE_HIHAT_CLOSED                     = $0e  ; 14
SAMPLE_JEWS_HARP                        = $0f  ; 15
SAMPLE_HIHAT_OPEN                       = $10  ; 16
SAMPLE_CRASH_CYMBAL                     = $11  ; 17
SAMPLE_BREATH                           = $12  ; 18
SAMPLE_SNARE_ACOUSTIC                   = $13  ; 19
SAMPLE_FOOTSTEP                         = $14  ; 20
SAMPLE_TIMPANI                          = $15  ; 21
SAMPLE_TOM_TOM                          = $16  ; 22
SAMPLE_PIZZ_BASS                        = $17  ; 23
SAMPLE_PIZZ_STRINGS                     = $18  ; 24
SAMPLE_TUBA                             = $19  ; 25
SAMPLE_HARP                             = $1a  ; 26
SAMPLE_BASS_PICK                        = $1b  ; 27
SAMPLE_MANDOLIN                         = $1c  ; 28
SAMPLE_GUITAR_DIST                      = $1d  ; 29
SAMPLE_WHISTLE                          = $1e  ; 30
SAMPLE_CELESTA                          = $1f  ; 31
SAMPLE_SNARE_ELECTRIC                   = $20  ; 32
SAMPLE_KICK_DRUM                        = $21  ; 33
SAMPLE_COWBELL                          = $22  ; 34
SAMPLE_BELL                             = $23  ; 35
SAMPLE_PIPE_ORGAN                       = $24  ; 36
SAMPLE_LAUGH                            = $25  ; 37
SAMPLE_CHOCOBO_1                        = $26  ; 38
SAMPLE_CHOCOBO_2                        = $27  ; 39
SAMPLE_CHOCOBO_3                        = $28  ; 40
SAMPLE_FINGER_SNAP                      = $29  ; 41
SAMPLE_RIMSHOT                          = $2a  ; 42
SAMPLE_CONTRABASS                       = $2b  ; 43
SAMPLE_RATCHET                          = $2c  ; 44
SAMPLE_BONGO                            = $2d  ; 45
SAMPLE_SHAKER                           = $2e  ; 46
SAMPLE_WOOD_BLOCK                       = $2f  ; 47
SAMPLE_MUSIC_BOX                        = $30  ; 48
SAMPLE_GUITAR_NYLON                     = $31  ; 49
SAMPLE_BAGPIPES                         = $32  ; 50
SAMPLE_SHAKUHACHI                       = $33  ; 51
SAMPLE_TOWN_1                           = $34  ; 52
SAMPLE_TOWN_2                           = $35  ; 53
SAMPLE_SLEIGH_BELLS                     = $36  ; 54
SAMPLE_VOICE_TENOR                      = $37  ; 55
SAMPLE_VOICE_BARITONE                   = $38  ; 56
SAMPLE_VOICE_ALTO                       = $39  ; 57
SAMPLE_PIPE_ORGAN_LOW                   = $3a  ; 58
SAMPLE_DEVIL_SFX_1                      = $3b  ; 59
SAMPLE_DEVIL_SFX_2                      = $3c  ; 60
SAMPLE_XYLOPHONE                        = $3d  ; 61
SAMPLE_CROWD_NOISE                      = $3e  ; 62

SAMPLE_BRR_ARRAY_LENGTH                 = $3f  ; 64

.endif
.list on
