; ------------------------------------------------------------------------------

.include "gfx/map_pal.inc"

; ------------------------------------------------------------------------------

.segment "map_pal"

; ed/c480
MapPal:
.incbin "map_pal/figaro.pal"
.incbin "map_pal/village_ext_1.pal"
.incbin "map_pal/doma.pal"
.incbin "map_pal/town_ext_1.pal"
.incbin "map_pal/docks.pal"
.incbin "map_pal/caves_1.pal"
.incbin "map_pal/castle_int.pal"
.incbin "map_pal/river.pal"
.incbin "map_pal/imp_camp.pal"
.incbin "map_pal/mountains_int.pal"
.incbin "map_pal/town_int_1.pal"
.incbin "map_pal/opera_1.pal"
.incbin "map_pal/narshe_ext.pal"
.incbin "map_pal/snowfields.pal"
.incbin "map_pal/train_ext.pal"
.incbin "map_pal/train_int.pal"
.incbin "map_pal/zozo_ext_1.pal"
.incbin "map_pal/vector.pal"
.incbin "map_pal/caves_2.pal"
.incbin "map_pal/floating_island.pal"
.incbin "map_pal/zozo_int.pal"
.incbin "map_pal/caves_3.pal"
.incbin "map_pal/village_ext_3.pal"
.incbin "map_pal/mountains_ext_1.pal"
.incbin "map_pal/magitek_factory.pal"
.incbin "map_pal/airship_ext_1.pal"
.incbin "map_pal/airship_int.pal"
.incbin "map_pal/cyans_dream.pal"
.incbin "map_pal/forest.pal"
.incbin "map_pal/imp_castle_ext.pal"
.incbin "map_pal/beach.pal"
.incbin "map_pal/imp_castle_int.pal"
.incbin "map_pal/caves_4.pal"
.incbin "map_pal/sealed_gate.pal"
.incbin "map_pal/kefkas_tower_1.pal"
.incbin "map_pal/burning_building.pal"
.incbin "map_pal/town_int_2.pal"
.incbin "map_pal/narshe_int.pal"
.incbin "map_pal/village_ext_2.pal"
.incbin "map_pal/opera_2.pal"
.incbin "map_pal/darills_tomb_1.pal"
.incbin "map_pal/town_ext_2.pal"
.incbin "map_pal/zozo_ext_2.pal"
.incbin "map_pal/kefkas_tower_2.pal"
.incbin "map_pal/cliffs.pal"
.incbin "map_pal/airship_ext_2.pal"
.incbin "map_pal/darills_tomb_2.pal"
.incbin "map_pal/mountains_ext_2.pal"

; ------------------------------------------------------------------------------
