; ------------------------------------------------------------------------------

.include "gfx/map_sprite_gfx.inc"

; ------------------------------------------------------------------------------

.macro inc_map_sprite_gfx id, name
        array_item MapSpriteGfx, {MAP_SPRITE_GFX::id} := *
        .incbin .sprintf("map_sprite_gfx/%s.4bpp", name)
.endmac

; ------------------------------------------------------------------------------

.segment "map_sprite_gfx"

MapSpriteGfx:

inc_map_sprite_gfx TERRA, "terra"
inc_map_sprite_gfx LOCKE, "locke"
inc_map_sprite_gfx CYAN, "cyan"
inc_map_sprite_gfx SHADOW, "shadow"
inc_map_sprite_gfx EDGAR, "edgar"
inc_map_sprite_gfx SABIN, "sabin"
inc_map_sprite_gfx CELES, "celes"
inc_map_sprite_gfx STRAGO, "strago"
inc_map_sprite_gfx RELM, "relm"
inc_map_sprite_gfx SETZER, "setzer"
inc_map_sprite_gfx MOG, "mog"
inc_map_sprite_gfx GAU, "gau"
inc_map_sprite_gfx GOGO, "gogo"
inc_map_sprite_gfx UMARO, "umaro"
inc_map_sprite_gfx SOLDIER, "soldier"
inc_map_sprite_gfx IMP, "imp"
inc_map_sprite_gfx LEO, "leo"
inc_map_sprite_gfx BANON, "banon"
inc_map_sprite_gfx ESPER_TERRA, "esper_terra"
inc_map_sprite_gfx MERCHANT, "merchant"
inc_map_sprite_gfx GHOST, "ghost"
inc_map_sprite_gfx KEFKA, "kefka"
inc_map_sprite_gfx GESTAHL, "gestahl"
inc_map_sprite_gfx OLD_MAN, "old_man"
inc_map_sprite_gfx MAN, "man"
inc_map_sprite_gfx DOG, "dog"
inc_map_sprite_gfx CELES_DRESS, "celes_dress"
inc_map_sprite_gfx RICH_MAN, "rich_man"
inc_map_sprite_gfx DRACO, "draco"
inc_map_sprite_gfx ARVIS, "arvis"
inc_map_sprite_gfx PILOT, "pilot"
inc_map_sprite_gfx ULTROS, "ultros"
inc_map_sprite_gfx SPIFFY_GAU, "spiffy_gau"
inc_map_sprite_gfx HOOKER, "hooker"
inc_map_sprite_gfx CHANCELLOR, "chancellor"
inc_map_sprite_gfx BARAM, "baram"
inc_map_sprite_gfx OLD_WOMAN, "old_woman"
inc_map_sprite_gfx WOMAN, "woman"
inc_map_sprite_gfx BOY, "boy"
inc_map_sprite_gfx GIRL, "girl"
inc_map_sprite_gfx BIRD, "bird"
inc_map_sprite_gfx RACHEL, "rachel"
inc_map_sprite_gfx KATARIN, "katarin"
inc_map_sprite_gfx IMPRESARIO, "impresario"
inc_map_sprite_gfx ESPER_ELDER, "esper_elder"
inc_map_sprite_gfx YURA, "yura"
inc_map_sprite_gfx SIEGFRIED, "siegfried"
inc_map_sprite_gfx CID, "cid"
inc_map_sprite_gfx MADUIN, "maduin"
inc_map_sprite_gfx BANDIT, "bandit"
inc_map_sprite_gfx VARGAS, "vargas"
inc_map_sprite_gfx MONSTER, "monster"
inc_map_sprite_gfx NARSHE_GUARD, "narshe_guard"
inc_map_sprite_gfx TRAIN_CONDUCTOR, "train_conductor"
inc_map_sprite_gfx SHOPKEEPER, "shopkeeper"
inc_map_sprite_gfx FAERIE, "faerie"
inc_map_sprite_gfx WOLF, "wolf"
inc_map_sprite_gfx DRAGON, "dragon"
inc_map_sprite_gfx FISH, "fish"
inc_map_sprite_gfx FIGARO_GUARD, "figaro_guard"
inc_map_sprite_gfx DARILL, "darill"
inc_map_sprite_gfx CHUPON, "chupon"
inc_map_sprite_gfx EMPEROR_SERVANT, "emperor_servant"
inc_map_sprite_gfx RAMUH, "ramuh"
inc_map_sprite_gfx FIGARO_GUARD_RIDING, "figaro_guard_riding"
inc_map_sprite_gfx CELES_CHAINS, "celes_chains"
inc_map_sprite_gfx GAU_KUNG_FU, "gau_kung_fu"
inc_map_sprite_gfx GAU_BANDANA, "gau_bandana"
inc_map_sprite_gfx KING_DOMA, "king_doma"
inc_map_sprite_gfx NUMBER_128, "number_128"
inc_map_sprite_gfx MAGI_WARRIOR_1, "magi_warrior_1"
inc_map_sprite_gfx SKULL_STATUE, "skull_statue"
inc_map_sprite_gfx IFRIT, "ifrit"
inc_map_sprite_gfx PHANTOM, "phantom"
inc_map_sprite_gfx SHIVA, "shiva"
inc_map_sprite_gfx UNICORN, "unicorn"
inc_map_sprite_gfx BISMARK, "bismark"
inc_map_sprite_gfx CARBUNCL, "carbuncl"
inc_map_sprite_gfx SHOAT, "shoat"
inc_map_sprite_gfx OWZER_1, "owzer_1"
inc_map_sprite_gfx OWZER_2, "owzer_2"
inc_map_sprite_gfx BLACKJACK, "blackjack"
inc_map_sprite_gfx FIGARO_GUARD_DEAD, "figaro_guard_dead"
inc_map_sprite_gfx NUMBER_024, "number_024"
inc_map_sprite_gfx TREASURE_CHEST, "treasure_chest"
inc_map_sprite_gfx MAGI_WARRIOR_2, "magi_warrior_2"
inc_map_sprite_gfx ATMA, "atma"
inc_map_sprite_gfx SMALL_STATUE, "small_statue"
inc_map_sprite_gfx FLOWERS, "flowers"
inc_map_sprite_gfx ENVELOPE, "envelope"
inc_map_sprite_gfx PLANT, "plant"
inc_map_sprite_gfx MAGICITE, "magicite"
inc_map_sprite_gfx BOOK, "book"
inc_map_sprite_gfx BABY, "baby"
inc_map_sprite_gfx QUESTION_MARK, "question_mark"
inc_map_sprite_gfx EXCLAMATION_POINT, "exclamation_point"
inc_map_sprite_gfx SLAVE_CROWN, "slave_crown"
inc_map_sprite_gfx WEIGHT, "weight"
inc_map_sprite_gfx BIRD_BANDANA, "bird_bandana"
inc_map_sprite_gfx EYES, "eyes"
inc_map_sprite_gfx BANDANA, "bandana"
inc_map_sprite_gfx NOTHING, "nothing"
inc_map_sprite_gfx FLYING_BIRD_1, "flying_bird_1"
inc_map_sprite_gfx FLYING_BIRD_2, "flying_bird_2"
inc_map_sprite_gfx BIG_SPARKLE, "big_sparkle"
inc_map_sprite_gfx MULTI_SPARKLES, "multi_sparkles"
inc_map_sprite_gfx SMALL_SPARKLE, "small_sparkle"
inc_map_sprite_gfx COIN, "coin"
inc_map_sprite_gfx RAT, "rat"
inc_map_sprite_gfx TURTLE, "turtle"
inc_map_sprite_gfx SMALL_BIRD_UP, "small_bird_up"
inc_map_sprite_gfx SAVE_POINT, "save_point"
inc_map_sprite_gfx FLAME, "flame"
inc_map_sprite_gfx EXPLOSION, "explosion"
inc_map_sprite_gfx TENTACLE_1, "tentacle_1"
inc_map_sprite_gfx TENTACLE_2, "tentacle_2"
inc_map_sprite_gfx BIG_SWITCH, "big_switch"
inc_map_sprite_gfx FLOOR_SWITCH, "floor_switch"
inc_map_sprite_gfx ROCK, "rock"
inc_map_sprite_gfx CRANE_HOOK_3, "crane_hook_3"
inc_map_sprite_gfx ELEVATOR, "elevator"
inc_map_sprite_gfx FLYING_TERRA_1, "flying_terra_1"
inc_map_sprite_gfx FLYING_TERRA_2, "flying_terra_2"
inc_map_sprite_gfx ENDING_TERRA_3, "ending_terra_3"
inc_map_sprite_gfx DIVING_HELMET, "diving_helmet"
inc_map_sprite_gfx GUARDIAN_1, "guardian_1"
inc_map_sprite_gfx GUARDIAN_2, "guardian_2"
inc_map_sprite_gfx GUARDIAN_3, "guardian_3"
inc_map_sprite_gfx CRANE_HOOK_2, "crane_hook_2"
inc_map_sprite_gfx GUARDIAN_4, "guardian_4"
inc_map_sprite_gfx GUARDIAN_5, "guardian_5"
inc_map_sprite_gfx GUARDIAN_6, "guardian_6"
inc_map_sprite_gfx CRANE_HOOK_1, "crane_hook_1"
inc_map_sprite_gfx MAGITEK_MACHINE, "magitek_machine"
inc_map_sprite_gfx GATE_1, "gate_1"
inc_map_sprite_gfx GATE_2, "gate_2"
inc_map_sprite_gfx GATE_3, "gate_3"
inc_map_sprite_gfx AIR_FORCE, "air_force"
inc_map_sprite_gfx LEO_SWORD, "leo_sword"
inc_map_sprite_gfx MAGITEK_TRAIN_1, "magitek_train_1"
inc_map_sprite_gfx MAGITEK_TRAIN_2, "magitek_train_2"
inc_map_sprite_gfx MAGITEK_TRAIN_3, "magitek_train_3"
inc_map_sprite_gfx MAGITEK_TRAIN_4, "magitek_train_4"
inc_map_sprite_gfx CRANE_1, "crane_1"
inc_map_sprite_gfx CRANE_2, "crane_2"
inc_map_sprite_gfx CRANE_3, "crane_3"
inc_map_sprite_gfx CHADARNOOK_1, "chadarnook_1"
inc_map_sprite_gfx CHADARNOOK_2, "chadarnook_2"
inc_map_sprite_gfx CHADARNOOK_3, "chadarnook_3"
inc_map_sprite_gfx FALCON_1, "falcon_1"
inc_map_sprite_gfx FALCON_2, "falcon_2"
inc_map_sprite_gfx FALCON_3, "falcon_3"
inc_map_sprite_gfx FLYING_TERRA_3, "flying_terra_3"
inc_map_sprite_gfx TRITOCH, "tritoch"
inc_map_sprite_gfx ODIN, "odin"
inc_map_sprite_gfx GODDESS_1, "goddess_1"
inc_map_sprite_gfx DOOM_1, "doom_1"
inc_map_sprite_gfx POLTERGEIST_1, "poltergeist_1"
inc_map_sprite_gfx GODDESS_2, "goddess_2"
inc_map_sprite_gfx GODDESS_3, "goddess_3"
inc_map_sprite_gfx DOOM_2, "doom_2"
inc_map_sprite_gfx DOOM_3, "doom_3"
inc_map_sprite_gfx ENDING_TERRA_1, "ending_terra_1"
inc_map_sprite_gfx ENDING_TERRA_2, "ending_terra_2"
inc_map_sprite_gfx SMALL_BIRD_LEFT, "small_bird_left"

; ------------------------------------------------------------------------------

; d8/3000
VehicleGfx:
.incbin "vehicle.4bpp"

; ------------------------------------------------------------------------------
