; ------------------------------------------------------------------------------

.include "gfx/map_sprite_gfx.inc"

; ------------------------------------------------------------------------------

.macro inc_map_sprite_gfx _id, _name
        .ident(.sprintf("MapSpriteGfx_%04x", _id)) := *
        .incbin .sprintf("map_sprite_gfx/%s.4bpp", _name)
.endmac

; ------------------------------------------------------------------------------

.segment "map_sprite_gfx"

MapSpriteGfx:

inc_map_sprite_gfx MAP_SPRITE_GFX_TERRA, "terra"
inc_map_sprite_gfx MAP_SPRITE_GFX_LOCKE, "locke"
inc_map_sprite_gfx MAP_SPRITE_GFX_CYAN, "cyan"
inc_map_sprite_gfx MAP_SPRITE_GFX_SHADOW, "shadow"
inc_map_sprite_gfx MAP_SPRITE_GFX_EDGAR, "edgar"
inc_map_sprite_gfx MAP_SPRITE_GFX_SABIN, "sabin"
inc_map_sprite_gfx MAP_SPRITE_GFX_CELES, "celes"
inc_map_sprite_gfx MAP_SPRITE_GFX_STRAGO, "strago"
inc_map_sprite_gfx MAP_SPRITE_GFX_RELM, "relm"
inc_map_sprite_gfx MAP_SPRITE_GFX_SETZER, "setzer"
inc_map_sprite_gfx MAP_SPRITE_GFX_MOG, "mog"
inc_map_sprite_gfx MAP_SPRITE_GFX_GAU, "gau"
inc_map_sprite_gfx MAP_SPRITE_GFX_GOGO, "gogo"
inc_map_sprite_gfx MAP_SPRITE_GFX_UMARO, "umaro"
inc_map_sprite_gfx MAP_SPRITE_GFX_SOLDIER, "soldier"
inc_map_sprite_gfx MAP_SPRITE_GFX_IMP, "imp"
inc_map_sprite_gfx MAP_SPRITE_GFX_LEO, "leo"
inc_map_sprite_gfx MAP_SPRITE_GFX_BANON, "banon"
inc_map_sprite_gfx MAP_SPRITE_GFX_ESPER_TERRA, "esper_terra"
inc_map_sprite_gfx MAP_SPRITE_GFX_MERCHANT, "merchant"
inc_map_sprite_gfx MAP_SPRITE_GFX_GHOST, "ghost"
inc_map_sprite_gfx MAP_SPRITE_GFX_KEFKA, "kefka"
inc_map_sprite_gfx MAP_SPRITE_GFX_GESTAHL, "gestahl"
inc_map_sprite_gfx MAP_SPRITE_GFX_OLD_MAN, "old_man"
inc_map_sprite_gfx MAP_SPRITE_GFX_MAN, "man"
inc_map_sprite_gfx MAP_SPRITE_GFX_DOG, "dog"
inc_map_sprite_gfx MAP_SPRITE_GFX_CELES_DRESS, "celes_dress"
inc_map_sprite_gfx MAP_SPRITE_GFX_RICH_MAN, "rich_man"
inc_map_sprite_gfx MAP_SPRITE_GFX_DRACO, "draco"
inc_map_sprite_gfx MAP_SPRITE_GFX_ARVIS, "arvis"
inc_map_sprite_gfx MAP_SPRITE_GFX_PILOT, "pilot"
inc_map_sprite_gfx MAP_SPRITE_GFX_ULTROS, "ultros"
inc_map_sprite_gfx MAP_SPRITE_GFX_SPIFFY_GAU, "spiffy_gau"
inc_map_sprite_gfx MAP_SPRITE_GFX_HOOKER, "hooker"
inc_map_sprite_gfx MAP_SPRITE_GFX_CHANCELLOR, "chancellor"
inc_map_sprite_gfx MAP_SPRITE_GFX_BARAM, "baram"
inc_map_sprite_gfx MAP_SPRITE_GFX_OLD_WOMAN, "old_woman"
inc_map_sprite_gfx MAP_SPRITE_GFX_WOMAN, "woman"
inc_map_sprite_gfx MAP_SPRITE_GFX_BOY, "boy"
inc_map_sprite_gfx MAP_SPRITE_GFX_GIRL, "girl"
inc_map_sprite_gfx MAP_SPRITE_GFX_BIRD, "bird"
inc_map_sprite_gfx MAP_SPRITE_GFX_RACHEL, "rachel"
inc_map_sprite_gfx MAP_SPRITE_GFX_KATARIN, "katarin"
inc_map_sprite_gfx MAP_SPRITE_GFX_IMPRESARIO, "impresario"
inc_map_sprite_gfx MAP_SPRITE_GFX_ESPER_ELDER, "esper_elder"
inc_map_sprite_gfx MAP_SPRITE_GFX_YURA, "yura"
inc_map_sprite_gfx MAP_SPRITE_GFX_SIEGFRIED, "siegfried"
inc_map_sprite_gfx MAP_SPRITE_GFX_CID, "cid"
inc_map_sprite_gfx MAP_SPRITE_GFX_MADUIN, "maduin"
inc_map_sprite_gfx MAP_SPRITE_GFX_BANDIT, "bandit"
inc_map_sprite_gfx MAP_SPRITE_GFX_VARGAS, "vargas"
inc_map_sprite_gfx MAP_SPRITE_GFX_MONSTER, "monster"
inc_map_sprite_gfx MAP_SPRITE_GFX_NARSHE_GUARD, "narshe_guard"
inc_map_sprite_gfx MAP_SPRITE_GFX_TRAIN_CONDUCTOR, "train_conductor"
inc_map_sprite_gfx MAP_SPRITE_GFX_SHOPKEEPER, "shopkeeper"
inc_map_sprite_gfx MAP_SPRITE_GFX_FAERIE, "faerie"
inc_map_sprite_gfx MAP_SPRITE_GFX_WOLF, "wolf"
inc_map_sprite_gfx MAP_SPRITE_GFX_DRAGON, "dragon"
inc_map_sprite_gfx MAP_SPRITE_GFX_FISH, "fish"
inc_map_sprite_gfx MAP_SPRITE_GFX_FIGARO_GUARD, "figaro_guard"
inc_map_sprite_gfx MAP_SPRITE_GFX_DARILL, "darill"
inc_map_sprite_gfx MAP_SPRITE_GFX_CHUPON, "chupon"
inc_map_sprite_gfx MAP_SPRITE_GFX_EMPEROR_SERVANT, "emperor_servant"
inc_map_sprite_gfx MAP_SPRITE_GFX_RAMUH, "ramuh"
inc_map_sprite_gfx MAP_SPRITE_GFX_FIGARO_GUARD_RIDING, "figaro_guard_riding"
inc_map_sprite_gfx MAP_SPRITE_GFX_CELES_CHAINS, "celes_chains"
inc_map_sprite_gfx MAP_SPRITE_GFX_GAU_KUNG_FU, "gau_kung_fu"
inc_map_sprite_gfx MAP_SPRITE_GFX_GAU_BANDANA, "gau_bandana"
inc_map_sprite_gfx MAP_SPRITE_GFX_KING_DOMA, "king_doma"
inc_map_sprite_gfx MAP_SPRITE_GFX_NUMBER_128, "number_128"
inc_map_sprite_gfx MAP_SPRITE_GFX_MAGI_WARRIOR_1, "magi_warrior_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_SKULL_STATUE, "skull_statue"
inc_map_sprite_gfx MAP_SPRITE_GFX_IFRIT, "ifrit"
inc_map_sprite_gfx MAP_SPRITE_GFX_PHANTOM, "phantom"
inc_map_sprite_gfx MAP_SPRITE_GFX_SHIVA, "shiva"
inc_map_sprite_gfx MAP_SPRITE_GFX_UNICORN, "unicorn"
inc_map_sprite_gfx MAP_SPRITE_GFX_BISMARK, "bismark"
inc_map_sprite_gfx MAP_SPRITE_GFX_CARBUNCL, "carbuncl"
inc_map_sprite_gfx MAP_SPRITE_GFX_SHOAT, "shoat"
inc_map_sprite_gfx MAP_SPRITE_GFX_OWZER_1, "owzer_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_OWZER_2, "owzer_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_BLACKJACK, "blackjack"
inc_map_sprite_gfx MAP_SPRITE_GFX_FIGARO_GUARD_DEAD, "figaro_guard_dead"
inc_map_sprite_gfx MAP_SPRITE_GFX_NUMBER_024, "number_024"
inc_map_sprite_gfx MAP_SPRITE_GFX_TREASURE_CHEST, "treasure_chest"
inc_map_sprite_gfx MAP_SPRITE_GFX_MAGI_WARRIOR_2, "magi_warrior_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_ATMA, "atma"
inc_map_sprite_gfx MAP_SPRITE_GFX_SMALL_STATUE, "small_statue"
inc_map_sprite_gfx MAP_SPRITE_GFX_FLOWERS, "flowers"
inc_map_sprite_gfx MAP_SPRITE_GFX_ENVELOPE, "envelope"
inc_map_sprite_gfx MAP_SPRITE_GFX_PLANT, "plant"
inc_map_sprite_gfx MAP_SPRITE_GFX_MAGICITE, "magicite"
inc_map_sprite_gfx MAP_SPRITE_GFX_BOOK, "book"
inc_map_sprite_gfx MAP_SPRITE_GFX_BABY, "baby"
inc_map_sprite_gfx MAP_SPRITE_GFX_QUESTION_MARK, "question_mark"
inc_map_sprite_gfx MAP_SPRITE_GFX_EXCLAMATION_POINT, "exclamation_point"
inc_map_sprite_gfx MAP_SPRITE_GFX_SLAVE_CROWN, "slave_crown"
inc_map_sprite_gfx MAP_SPRITE_GFX_WEIGHT, "weight"
inc_map_sprite_gfx MAP_SPRITE_GFX_BIRD_BANDANA, "bird_bandana"
inc_map_sprite_gfx MAP_SPRITE_GFX_EYES, "eyes"
inc_map_sprite_gfx MAP_SPRITE_GFX_BANDANA, "bandana"
inc_map_sprite_gfx MAP_SPRITE_GFX_NOTHING, "nothing"
inc_map_sprite_gfx MAP_SPRITE_GFX_FLYING_BIRD_1, "flying_bird_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_FLYING_BIRD_2, "flying_bird_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_BIG_SPARKLE, "big_sparkle"
inc_map_sprite_gfx MAP_SPRITE_GFX_MULTI_SPARKLES, "multi_sparkles"
inc_map_sprite_gfx MAP_SPRITE_GFX_SMALL_SPARKLE, "small_sparkle"
inc_map_sprite_gfx MAP_SPRITE_GFX_COIN, "coin"
inc_map_sprite_gfx MAP_SPRITE_GFX_RAT, "rat"
inc_map_sprite_gfx MAP_SPRITE_GFX_TURTLE, "turtle"
inc_map_sprite_gfx MAP_SPRITE_GFX_SMALL_BIRD_UP, "small_bird_up"
inc_map_sprite_gfx MAP_SPRITE_GFX_SAVE_POINT, "save_point"
inc_map_sprite_gfx MAP_SPRITE_GFX_FLAME, "flame"
inc_map_sprite_gfx MAP_SPRITE_GFX_EXPLOSION, "explosion"
inc_map_sprite_gfx MAP_SPRITE_GFX_TENTACLE_1, "tentacle_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_TENTACLE_2, "tentacle_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_BIG_SWITCH, "big_switch"
inc_map_sprite_gfx MAP_SPRITE_GFX_FLOOR_SWITCH, "floor_switch"
inc_map_sprite_gfx MAP_SPRITE_GFX_ROCK, "rock"
inc_map_sprite_gfx MAP_SPRITE_GFX_CRANE_HOOK_3, "crane_hook_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_ELEVATOR, "elevator"
inc_map_sprite_gfx MAP_SPRITE_GFX_FLYING_TERRA_1, "flying_terra_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_FLYING_TERRA_2, "flying_terra_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_ENDING_TERRA_3, "ending_terra_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_DIVING_HELMET, "diving_helmet"
inc_map_sprite_gfx MAP_SPRITE_GFX_GUARDIAN_1, "guardian_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_GUARDIAN_2, "guardian_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_GUARDIAN_3, "guardian_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_CRANE_HOOK_2, "crane_hook_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_GUARDIAN_4, "guardian_4"
inc_map_sprite_gfx MAP_SPRITE_GFX_GUARDIAN_5, "guardian_5"
inc_map_sprite_gfx MAP_SPRITE_GFX_GUARDIAN_6, "guardian_6"
inc_map_sprite_gfx MAP_SPRITE_GFX_CRANE_HOOK_1, "crane_hook_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_MAGITEK_MACHINE, "magitek_machine"
inc_map_sprite_gfx MAP_SPRITE_GFX_GATE_1, "gate_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_GATE_2, "gate_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_GATE_3, "gate_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_AIR_FORCE, "air_force"
inc_map_sprite_gfx MAP_SPRITE_GFX_LEO_SWORD, "leo_sword"
inc_map_sprite_gfx MAP_SPRITE_GFX_MAGITEK_TRAIN_1, "magitek_train_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_MAGITEK_TRAIN_2, "magitek_train_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_MAGITEK_TRAIN_3, "magitek_train_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_MAGITEK_TRAIN_4, "magitek_train_4"
inc_map_sprite_gfx MAP_SPRITE_GFX_CRANE_1, "crane_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_CRANE_2, "crane_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_CRANE_3, "crane_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_CHADARNOOK_1, "chadarnook_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_CHADARNOOK_2, "chadarnook_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_CHADARNOOK_3, "chadarnook_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_FALCON_1, "falcon_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_FALCON_2, "falcon_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_FALCON_3, "falcon_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_FLYING_TERRA_3, "flying_terra_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_TRITOCH, "tritoch"
inc_map_sprite_gfx MAP_SPRITE_GFX_ODIN, "odin"
inc_map_sprite_gfx MAP_SPRITE_GFX_GODDESS_1, "goddess_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_DOOM_1, "doom_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_POLTERGEIST_1, "poltergeist_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_GODDESS_2, "goddess_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_GODDESS_3, "goddess_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_DOOM_2, "doom_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_DOOM_3, "doom_3"
inc_map_sprite_gfx MAP_SPRITE_GFX_ENDING_TERRA_1, "ending_terra_1"
inc_map_sprite_gfx MAP_SPRITE_GFX_ENDING_TERRA_2, "ending_terra_2"
inc_map_sprite_gfx MAP_SPRITE_GFX_SMALL_BIRD_LEFT, "small_bird_left"

; ------------------------------------------------------------------------------

; d8/3000
VehicleGfx:
.incbin "vehicle.4bpp"

; ------------------------------------------------------------------------------
