.global World1BGPal, World2BGPal, World1SpritePal, World2SpritePal
.global VectorApproachGfx, VectorApproachTiles, World3Pal
.global WorldBackdropGfxPtr, WorldBackdropTilesPtr
.global AirshipGfx1Ptr, WorldTilemap1Ptr, WorldGfx1Ptr, MagitekTrainGfxPtr
.global MagitekTrainPalPtr, WorldGfx2Ptr, WorldTilemap2Ptr, WorldTilemap3Ptr
.global WorldGfx3Ptr, WorldChocoGfx1Ptr, VectorApproachPalPtr, WorldEsperTerraPalPtr
.global WorldAnimSpriteGfxPtr, WorldMiscSpriteGfxPtr, WorldChocoGfx2Ptr
.global MinimapGfx1Ptr, MinimapGfx2Ptr, AirshipGfx2Ptr, EndingAirshipPalPtr
