.ifndef MAP_PARALLAX_INC
MAP_PARALLAX_INC = 1

.enum MAP_PARALLAX
        NONE                            ; 0
        PHANTOM_FOREST                  ; 1
        FOG_PARALLAX                    ; 2
        TRAIN                           ; 3
        PARALLAX                        ; 4
        OPERA_HOUSE                     ; 5
        FLOATING_ISLAND                 ; 6
        MAP_PARALLAX_7                  ; 7
        AIRSHIP                         ; 8
        SEALED_GATE                     ; 9
        FOG                             ; 10
        FAST_FOG                        ; 11
        AIRSHIP_CRASHING                ; 12
        SLOW_FOG                        ; 13
        FANATICS_TOWER                  ; 14
        KEFKAS_TOWER_TOP                ; 15
        MAP_PARALLAX_16                 ; 16
        WATERFALL                       ; 17
        KEFKAS_TOWER                    ; 18
        MAP_PARALLAX_19                 ; 19
        MAP_PARALLAX_20                 ; 20
.endenum

.endif